// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#SOVQPOOOVQPO'#CaOVQPO'#CbOOQO'#Ch'#ChOOQO'#Cc'#CcQVQPOOOhQPO,58{OoQPO,58|OOQO-E6a-E6aOOQO1G.g1G.gOOQO1G.h1G.hOyQPO1G.hOOQO'#Cd'#CdO!OQPO7+$SOOQO-E6b-E6bOOQO<<Gn<<Gn",
  stateData: "!W~OZOS~OQRORROSRO]PO_QO~O^XO~PVO`ZOaYO~PVOR[O~OR[Oa_O~O",
  goto: "!S]PPPPP^^ftPPPz]ROPQTUVQTOQUPQVQVWTUVQ]ZR^]]SOPQTUV",
  nodeNames: "⚠ File Identifier Number String Permutations WeightedExpression",
  maxTerm: 17,
  nodeProps: [
    ["group", -5,2,3,4,5,6,"Expression"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "$t~RdX^!apq!ars#Uxy#syz#x!Q![#}![!]$V!c!}$[#R#S$[#T#o$[#o#p$j#q#r$o#y#z!a$f$g!a#BY#BZ!a$IS$I_!a$I|$JO!a$JT$JU!a$KV$KW!a&FU&FV!a~!fYZ~X^!apq!a#y#z!a$f$g!a#BY#BZ!a$IS$I_!a$I|$JO!a$JT$JU!a$KV$KW!a&FU&FV!a~#XTOr#Urs#hs;'S#U;'S;=`#m<%lO#U~#mOS~~#pP;=`<%l#U~#xO_~~#}Oa~~$SPR~!Q![#}~$[O`~~$aRQ~!c!}$[#R#S$[#T#o$[~$oO]~~$tO^~",
  tokenizers: [0],
  topRules: {"File":[0,1]},
  tokenPrec: 0
})
