export type PromptLangNodeName =
    | 'WeightedExpression'
    | 'Permutations'
    | 'Lora'
    | 'Embedding'
    | 'Wildcards'
    | 'Separator'
    | 'Break'
    | 'Identifier'
    | 'Number'
    | 'String'
