// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$zOVQPOOOVQPO'#C^OVQPO'#C`OzQPO'#CaO!SQPO'#CeO![QPO'#CgO!dQPO'#CiOOQO'#Cr'#CrOOQO'#Cn'#CnQVQPOOO!lQPO,58xO!sQPO,58zOOQO'#Cb'#CbO!zQPO,58{OOQO'#Cf'#CfOOQO,59P,59POOQO'#Ch'#ChOOQO,59R,59ROOQO'#Cj'#CjOOQO,59T,59TOOQO-E6l-E6lO#{QQO1G.dOOQO1G.f1G.fO$QQQO1G.gOOQO7+$O7+$OO$VQQO7+$ROOQO<<Gm<<GmO$_QQO<<GmO$dQPOAN=XOOQOG22sG22s",
  stateData: "$n~OeOS~OVVOWVO_VO`VOaVOgPOiQOkROoSOpTOqUO~OV[OW[O~OV^OW^O~OV`OW`O~OVbOWbO~OheO~PVOjfO~PVOlgOVTaWTa_Ta`TaaTacTagTaiTakTaoTapTaqTahTajTa~ORhO~ORiO~OmkOnjO~ORlO~OnmO~Oa`V`~",
  goto: "!dgPPhPhhpPPhshvhyPPP|PPP![]VOPQXYZR]RR_SRaTRcUQXOQYPQZQVdXYZ]WOPQXYZ",
  nodeNames: "⚠ File WeightedExpression Number Permutations Lora LoraName Identifier String Wildcard WildcardName Embedding EmbeddingName Tag TagName Separator Break Comment",
  maxTerm: 33,
  nodeProps: [
    ["group", -11,2,4,5,7,8,9,11,13,15,16,17,"Expression"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: ",R~RqX^#Ypq#Yrs#}uv$lxy$qyz$v|}%R}!O%Y!O!P&f!P!Q%w!Q![&f![!]'V!]!^'[!a!b's!b!c'x!c!}%w!}#O'}#O#P%w#P#Q(S#R#S%w#T#U%w#U#V(X#V#o%w#o#p+w#q#r+|#y#z#Y$f$g#Y#BY#BZ#Y$IS$I_#Y$I|$JO#Y$JT$JU#Y$KV$KW#Y&FU&FV#Y~#_Ye~X^#Ypq#Y#y#z#Y$f$g#Y#BY#BZ#Y$IS$I_#Y$I|$JO#Y$JT$JU#Y$KV$KW#Y&FU&FV#Y~$QTOr#}rs$as;'S#};'S;=`$f<%lO#}~$fOW~~$iP;=`<%l#}~$qOq~~$vOg~~$yPz{$|~%ROh~R%YOmQ_PR%_WVP}!O%w!O!P&f!P!Q%w!Q![&f!c!}%w#O#P%w#R#S%w#T#o%wP%|WVP}!O%w!O!P%w!P!Q%w!Q![%w!c!}%w#O#P%w#R#S%w#T#o%wR&mWRQVP}!O%w!O!P&f!P!Q%w!Q![&f!c!}%w#O#P%w#R#S%w#T#o%w~'[Op~~'aSa~OY'[Z;'S'[;'S;=`'m<%lO'[~'pP;=`<%l'[~'xOo~~'}Ok~~(SOl~~(XOn~~(^YVP}!O%w!O!P%w!P!Q%w!Q![%w!c!}%w#O#P%w#R#S%w#T#f%w#f#g(|#g#o%w~)RYVP}!O%w!O!P%w!P!Q%w!Q![%w!c!}%w#O#P%w#R#S%w#T#X%w#X#Y)q#Y#o%w~)vXVP}!O%w!O!P%w!P!Q%w!Q![%w!c!}%w#O#P%w#R#S%w#T#U*c#U#o%w~*hYVP}!O%w!O!P%w!P!Q%w!Q![%w!c!}%w#O#P%w#R#S%w#T#_%w#_#`+W#`#o%w~+_W`~VP}!O%w!O!P%w!P!Q%w!Q![%w!c!}%w#O#P%w#R#S%w#T#o%w~+|Oi~~,ROj~",
  tokenizers: [0, 1],
  topRules: {"File":[0,1]},
  tokenPrec: 163
})
