// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$zOVQPOOOVQPO'#C^OVQPO'#C`O}QPO'#CaO!VQPO'#CeO!_QPO'#CgO!gQPO'#CiOOQO'#Cr'#CrOOQO'#Cn'#CnQVQPOOO!oQPO,58xO!vQPO,58zOOQO'#Cb'#CbO!}QPO,58{OOQO'#Cf'#CfOOQO,59P,59POOQO'#Ch'#ChOOQO,59R,59ROOQO'#Cj'#CjOOQO,59T,59TOOQO-E6l-E6lO$RQPO1G.dOOQO1G.f1G.fO$WQPO1G.gOOQO7+$O7+$OO$]QQO7+$ROOQO<<Gm<<GmO$eQPO<<GmO$jQPOAN=XOOQOG22sG22s",
  stateData: "$u~OeOS~ORVOVVOWVO_VO`VOaVOgPOiQOkROoSOpTOqUO~OV[OW[O~OV^OW^O~OV`OW`O~OVbOWbO~OheO~PVOjfO~PVOlgORTaVTaWTa_Ta`TaaTacTagTaiTakTaoTapTaqTahTajTa~ORhO~ORiO~OmkOnjO~ORlO~OnmO~OaR`V`~",
  goto: "!dgPPhPhhpPPhshvhyPPP|PPP![]VOPQXYZR]RR_SRaTRcUQXOQYPQZQVdXYZ]WOPQXYZ",
  nodeNames: "⚠ File WeightedExpression Number Permutations Lora LoraName Identifier String Wildcard WildcardName Embedding EmbeddingName Tag TagName Separator Break Comment",
  maxTerm: 33,
  nodeProps: [
    ["group", -12,2,3,4,5,7,8,9,11,13,15,16,17,"Expression"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "(}~RoX^#Spq#Srs#wuv$fxy$kyz$p|}${}!O%S!O!P%S!Q![%S![!]%b!]!^%g!a!b&O!b!c&T!c!}&Y!}#O&h#P#Q&m#R#S&Y#T#U&Y#U#V&r#V#o&Y#o#p(s#q#r(x#y#z#S$f$g#S#BY#BZ#S$IS$I_#S$I|$JO#S$JT$JU#S$KV$KW#S&FU&FV#S~#XYe~X^#Spq#S#y#z#S$f$g#S#BY#BZ#S$IS$I_#S$I|$JO#S$JT$JU#S$KV$KW#S&FU&FV#S~#zTOr#wrs$Zs;'S#w;'S;=`$`<%lO#w~$`OW~~$cP;=`<%l#w~$kOq~~$pOg~~$sPz{$v~${Oh~R%SOmQ_P~%XRR~}!O%S!O!P%S!Q![%S~%gOp~~%lSa~OY%gZ;'S%g;'S;=`%x<%lO%g~%{P;=`<%l%g~&TOo~~&YOk~~&_RV~!c!}&Y#R#S&Y#T#o&Y~&mOl~~&rOn~~&wTV~!c!}&Y#R#S&Y#T#f&Y#f#g'W#g#o&Y~']TV~!c!}&Y#R#S&Y#T#X&Y#X#Y'l#Y#o&Y~'qSV~!c!}&Y#R#S&Y#T#U'}#U#o&Y~(STV~!c!}&Y#R#S&Y#T#_&Y#_#`(c#`#o&Y~(jR`~V~!c!}&Y#R#S&Y#T#o&Y~(xOi~~(}Oj~",
  tokenizers: [0, 1],
  topRules: {"File":[0,1]},
  tokenPrec: 169
})
