// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Prompt = 1,
  WeightedExpression = 2,
  Content = 3,
  Number = 4,
  Permutations = 5,
  Lora = 6,
  Identifier = 7,
  String = 8,
  Wildcard = 9,
  Embedding = 10,
  Tag = 11,
  TagName = 12,
  Separator = 13,
  Break = 14,
  Comment = 15
