// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  File = 1,
  WeightedExpression = 2,
  Number = 3,
  Permutations = 4,
  Lora = 5,
  LoraName = 6,
  Identifier = 7,
  String = 8,
  Wildcard = 9,
  WildcardName = 10,
  Embedding = 11,
  EmbeddingName = 12,
  Tag = 13,
  TagName = 14,
  Separator = 15,
  Break = 16,
  Comment = 17
