// prettier-ignore
export type KnownCustomNode_Title =
    | "✨ Clarity AI - Creative Image Upscaler and Enhancer for ComfyUI"
    | "🐰 MaraScott Nodes"
    | "😸 YFG Comical Nodes"
    | "a-person-mask-generator"
    | "A8R8 ComfyUI Nodes"
    | "abg-comfyui"
    | "abracadabra-comfyui"
    | "advance-aesthetic-score"
    | "Advanced CLIP Text Encode"
    | "Advanced Latent Control"
    | "AegisFlow Utility Nodes"
    | "AIGODLIKE-ComfyUI-Studio"
    | "AIGODLIKE-COMFYUI-TRANSLATION"
    | "AlekPet/ComfyUI_Custom_Nodes_AlekPet"
    | "alkemann nodes"
    | "Allor Plugin"
    | "Amazon Bedrock nodes for ComfyUI"
    | "AnimateDiff"
    | "AnimateDiff Evolved"
    | "Animatediff MotionLoRA Trainer"
    | "Anime Character Segmentation node for comfyui"
    | "antrobots ComfyUI Nodepack"
    | "Anyline"
    | "APISR IN COMFYUI"
    | "As_ComfyUI_CustomNodes"
    | "asagi4/comfyui-utility-nodes"
    | "ASTERR"
    | "asymmetric-tiling-comfyui"
    | "attention-couple-ComfyUI"
    | "auto nodes layout"
    | "Auto-MBW"
    | "Avatar Graph"
    | "Batch Rembg for ComfyUI"
    | "Batch-Condition-ComfyUI"
    | "BilboX's ComfyUI Custom Nodes"
    | "Bmad Nodes"
    | "Bounding Box Crop Node for ComfyUI"
    | "braintacles-nodes"
    | "BrevImage"
    | "BrushNet"
    | "bsz-cui-extras"
    | "Canvas Tab"
    | "cd-tuner_negpip-ComfyUI"
    | "cgem156-ComfyUI🍌"
    | "Chaosaiart-Nodes"
    | "Character Face Swap"
    | "Chatbox Overlay node for ComfyUI"
    | "CLIP Directional Prompt Attention"
    | "CLIP with BREAK syntax"
    | "CLIPSeg"
    | "Color Enhance"
    | "color2rgb"
    | "Comfy AI DoubTech.ai Image Sumission Node"
    | "Comfy Cloud"
    | "Comfy Couple"
    | "Comfy UI FatLabels"
    | "Comfy UI Online Loaders"
    | "Comfy UI Prompt Agent"
    | "Comfy UI QR Codes"
    | "comfy_clip_blip_node"
    | "comfy_http_request"
    | "Comfy_KepKitchenSink"
    | "Comfy_KepListStuff"
    | "Comfy_KepMatteAnything"
    | "comfy_meh"
    | "comfy_PoP"
    | "comfy-easy-grids"
    | "Comfy-LFO"
    | "comfy-mecha"
    | "comfy-nodes"
    | "Comfy-Photoshop-SD"
    | "comfy-plasma"
    | "Comfy-RVC"
    | "Comfy-Topaz"
    | "ComfyBreakAnim"
    | "comfygen"
    | "ComfyI2I"
    | "ComfyKit Custom Nodes"
    | "ComfyLiterals"
    | "ComfyMath"
    | "ComfyQR"
    | "ComfyQR-scanning-nodes"
    | "Comfyroll Studio"
    | "ComfyS3"
    | "ComfyUI - Apply LoRA Stacker with DARE"
    | "ComfyUI - Mask Bounding Box"
    | "ComfyUI - Native DynamiCrafter"
    | "ComfyUI - P2LDGAN Node"
    | "ComfyUI - Text Overlay Plugin"
    | "ComfyUI 3D Pose Editor"
    | "ComfyUI A1111-like Prompt Custom Node Solution"
    | "ComfyUI AceNodes"
    | "ComfyUI Aesthetic Predictor V2.5"
    | "ComfyUI aichemy nodes"
    | "ComfyUI AnyNode: Any Node you ask for"
    | "ComfyUI Assistant"
    | "ComfyUI Better Strings"
    | "ComfyUI Bringing Old Photos Back to Life"
    | "ComfyUI Browser"
    | "ComfyUI Caching Embeddings"
    | "ComfyUI Checkpoint Automatic Config"
    | "ComfyUI Clear Screen"
    | "ComfyUI Color Detection Nodes"
    | "ComfyUI CustomScheduler"
    | "ComfyUI Cutoff"
    | "ComfyUI DDColor"
    | "ComfyUI Deepface"
    | "ComfyUI Deploy"
    | "ComfyUI Depth Anything TensorRT"
    | "ComfyUI Diffusion Color Grading"
    | "ComfyUI Discopixel Nodes"
    | "ComfyUI DPM++ 2M Alt Sampler"
    | "ComfyUI Dreamtalk"
    | "ComfyUI Easy Padding"
    | "ComfyUI Easy Use"
    | "ComfyUI Essentials"
    | "ComfyUI ExLlamaV2 Nodes"
    | "ComfyUI Extra Samplers"
    | "ComfyUI fabric"
    | "ComfyUI Face Similarity"
    | "ComfyUI Fictiverse Nodes"
    | "ComfyUI Floodgate"
    | "ComfyUI Fooocus Nodes"
    | "ComfyUI for InstructIR"
    | "ComfyUI Frame Interpolation"
    | "ComfyUI Frame Maker"
    | "ComfyUI Griptape Nodes"
    | "ComfyUI HiDiffusion"
    | "Comfyui HiFORCE Plugin"
    | "ComfyUI Image Saver"
    | "ComfyUI Impact Pack"
    | "ComfyUI Inpaint Nodes"
    | "ComfyUI Inspire Pack"
    | "ComfyUI InstantID (Native Support)"
    | "ComfyUI InstantID Faceswapper"
    | "ComfyUI Invisible Watermark"
    | "ComfyUI Iterative Mixing Nodes"
    | "ComfyUI jank HiDiffusion"
    | "Comfyui lama remover"
    | "ComfyUI Layer Style"
    | "ComfyUI LayerDivider"
    | "ComfyUI LLaVA Captioner"
    | "ComfyUI Load and Save file to S3"
    | "ComfyUI Loopchain"
    | "ComfyUI Menu Anchor"
    | "ComfyUI MiniCPM-V"
    | "ComfyUI MotionDiff"
    | "ComfyUI Multi-Workspace"
    | "ComfyUI MuseV Evolved"
    | "ComfyUI Neural Network Latent Upscale"
    | "ComfyUI Nich Utils"
    | "ComfyUI NodePresets"
    | "ComfyUI NodeReset"
    | "ComfyUI Nodes for External Tooling"
    | "ComfyUI Noise"
    | "ComfyUI Ollama"
    | "ComfyUI OOTDiffusion"
    | "ComfyUI OpenVoice"
    | "ComfyUI Optical Flow"
    | "ComfyUI Pets"
    | "ComfyUI PhotoMaker (ZHO)"
    | "ComfyUI PhotoMaker Plus"
    | "ComfyUI PickScore Nodes"
    | "ComfyUI PiperTTS"
    | "ComfyUI PixelArt Detector"
    | "ComfyUI PNG Metadata"
    | "ComfyUI Preset Merger"
    | "ComfyUI Profiler"
    | "ComfyUI prompt control"
    | "ComfyUI Prompt ExtraNetworks"
    | "ComfyUI ProPainter Nodes"
    | "ComfyUI Ricing"
    | "ComfyUI roop"
    | "ComfyUI SchedulerMixer"
    | "ComfyUI SegMoE"
    | "ComfyUI Sequential Image Loader"
    | "ComfyUI Serving toolkit"
    | "ComfyUI SimpleTools Suit"
    | "ComfyUI Slothful Attention"
    | "ComfyUI Sokes Nodes"
    | "ComfyUI StabilityAI Suite"
    | "ComfyUI Stable Video Diffusion"
    | "ComfyUI StoryCreater"
    | "ComfyUI String Tools"
    | "ComfyUI Substring"
    | "ComfyUI Suno API"
    | "ComfyUI Tab Handler"
    | "ComfyUI Thumbnails"
    | "ComfyUI Universal Styler"
    | "ComfyUI Upscaler TensorRT"
    | "ComfyUI WD 1.4 Tagger"
    | "Comfyui Webcam capture node"
    | "ComfyUI Whisper"
    | "ComfyUI Workspace Manager - Comfyspace"
    | "ComfyUI Yolov8"
    | "ComfyUI YoloWorld-EfficientSAM"
    | "comfyui_ab_sampler"
    | "ComfyUI_alkaid"
    | "ComfyUI_Aniportrait"
    | "ComfyUI_API_Manager"
    | "ComfyUI_aspect_ratios"
    | "comfyui_auto_danbooru"
    | "ComfyUI_BadgerTools"
    | "ComfyUI_BattlemapGrid"
    | "ComfyUI_Blender_Texdiff"
    | "comfyui_bmab"
    | "ComfyUI_CartoonSegmentation"
    | "ComfyUI_Change_IMAGE_BOREDER"
    | "ComfyUI_ChatGLM_API"
    | "comfyui_cohere"
    | "ComfyUI_ColorMod"
    | "ComfyUI_CustomNet"
    | "ComfyUI_DanTagGen"
    | "comfyUI_DaVinciResolve"
    | "ComfyUI_demucus"
    | "ComfyUI_DiT [WIP]"
    | "ComfyUI_Dragos_Nodes"
    | "comfyui_DSP_imagehelpers"
    | "ComfyUI_experiments"
    | "comfyui_face_parsing"
    | "comfyui_facetools"
    | "ComfyUI_FastVAEDecorder_SDXL"
    | "ComfyUI_Fill-Nodes"
    | "ComfyUI_Fooocus_KSampler"
    | "ComfyUI_fsdymy"
    | "ComfyUI_GetFileNameFromURL"
    | "ComfyUI_GLM4Node"
    | "ComfyUI_GMIC"
    | "ComfyUI_GradientDeepShrink"
    | "ComfyUI_HF_Inference"
    | "ComfyUI_HiDiffusion_Pro"
    | "ComfyUI_Ib_CustomNodes"
    | "ComfyUI_ID_Animator"
    | "Comfyui_image2prompt"
    | "ComfyUI_ImageToText"
    | "comfyui_io_helpers"
    | "ComfyUI_IPAdapter_plus"
    | "Comfyui_joytag"
    | "ComfyUI_kkTranslator_nodes"
    | "comfyui_kmeans_filter"
    | "ComfyUI_KytraWebhookHTTP"
    | "ComfyUI_LiteLLM"
    | "ComfyUI_Llama3_8B"
    | "comfyui_LLM_party"
    | "ComfyUI_LLMVISION"
    | "ComfyUI_MagicClothing"
    | "comfyui_meanshift_filter"
    | "ComfyUI_Memeplex_DALLE"
    | "ComfyUI_Mexx_Poster"
    | "ComfyUI_Mexx_Styler"
    | "ComfyUI_MileHighStyler"
    | "ComfyUI_Mira"
    | "ComfyUI_ModelScopeT2V"
    | "ComfyUI_mozman_nodes"
    | "ComfyUI_MSSpeech_TTS"
    | "ComfyUI_NAIDGenerator"
    | "ComfyUI_NetDist"
    | "ComfyUI_Nimbus-Pack"
    | "comfyUI_Nodes_nicolai256"
    | "ComfyUI_NoxinNodes"
    | "ComfyUI_OOTDiffusion_CXH"
    | "ComfyUI_ParlerTTS"
    | "ComfyUI_PCDMs"
    | "ComfyUI_PerpWeight"
    | "ComfyUI_Pic2Story"
    | "ComfyUI_Pilgram"
    | "ComfyUI_Pipeline_Tool"
    | "comfyui_private_postprocessor"
    | "ComfyUI_Prompt-Quill"
    | "ComfyUI_pytorch_openpose"
    | "comfyui_quilting"
    | "ComfyUI_RErouter_CustomNodes"
    | "ComfyUI_rotate_image"
    | "ComfyUI_RSS_Feed_Reader"
    | "ComfyUI_SDXL_DreamBooth_LoRA_CustomNodes"
    | "ComfyUI_Seamless_Patten"
    | "ComfyUI_Seg_VITON"
    | "comfyui_segformer_b2_clothes"
    | "ComfyUI_Segment_Mask"
    | "ComfyUI_SendDiscord"
    | "comfyUI_SillyNodes"
    | "ComfyUI_StableCascadeLatentRatio"
    | "ComfyUI_StoryDiffusion"
    | "ComfyUI_StreamDiffusion"
    | "ComfyUI_StreamingT2V"
    | "ComfyUI_Strimmlarns_aesthetic_score"
    | "ComfyUi_String_Function_Tree"
    | "ComfyUI_SUNoise"
    | "comfyui_tag_filter"
    | "ComfyUI_Text"
    | "ComfyUI_TextAssets"
    | "ComfyUI_TGate"
    | "ComfyUI_tinyterraNodes"
    | "comfyUI_TJ_NormalLighting"
    | "ComfyUI_toyxyz_test_nodes"
    | "ComfyUI_TravelSuite"
    | "ComfyUI_V-Express"
    | "comfyui_visual_anagram"
    | "ComfyUI_VisualStylePrompting"
    | "comfyui_wfc_like"
    | "ComfyUI_WordCloud"
    | "ComfyUI_yanc"
    | "ComfyUI_zfkun"
    | "ComfyUI-0246"
    | "ComfyUI-3D-Pack"
    | "ComfyUI-Advanced-ControlNet"
    | "ComfyUI-Aimidi-nodes"
    | "ComfyUI-AIT"
    | "ComfyUI-Anchors"
    | "ComfyUI-AnimateAnyone-Evolved"
    | "ComfyUI-AnimateAnyone-reproduction"
    | "ComfyUI-AniPortrait"
    | "ComfyUI-APISR"
    | "comfyui-art-venture"
    | "ComfyUI-ArtGallery"
    | "ComfyUI-AudioReactive"
    | "ComfyUI-AudioReactor"
    | "ComfyUI-AudioScheduler"
    | "ComfyUI-AutoColorGimp"
    | "ComfyUI-AutoCropFaces"
    | "ComfyUI-AutoLabel"
    | "ComfyUI-AutomaticCFG"
    | "ComfyUI-AutoTrimBG"
    | "ComfyUI-Background-Replacement"
    | "ComfyUI-BadmanNodes"
    | "ComfyUI-BiRefNet"
    | "ComfyUI-BiRefNet-ZHO"
    | "ComfyUI-bleh"
    | "ComfyUI-Bmad-DirtyUndoRedo"
    | "ComfyUI-Book-Tools Nodes for ComfyUI"
    | "ComfyUI-BRIA_AI-RMBG"
    | "ComfyUI-BrushNet-Wrapper"
    | "ComfyUI-CADS"
    | "ComfyUI-Calculation"
    | "ComfyUI-CameraCtrl-Wrapper"
    | "ComfyUI-CascadeResolutions"
    | "ComfyUI-Catcat"
    | "ComfyUI-CCSR"
    | "ComfyUI-Champ"
    | "ComfyUI-Chat-GPT-Integration"
    | "ComfyUI-Chibi-Nodes"
    | "ComfyUI-ClipScore-Nodes"
    | "ComfyUI-ComfyRun"
    | "ComfyUI-ComfyWorkflows"
    | "ComfyUI-Comic"
    | "ComfyUI-Coziness"
    | "ComfyUI-Cre8it-Nodes"
    | "ComfyUI-CSV-Loader"
    | "ComfyUI-CUP"
    | "ComfyUI-DareMerge"
    | "ComfyUI-Dart"
    | "ComfyUI-DDColor"
    | "ComfyUI-Debug"
    | "ComfyUI-deepcache"
    | "comfyUI-DeepSeek-2lab"
    | "ComfyUI-depth-fm"
    | "ComfyUI-Depth-Visualization"
    | "ComfyUI-Dev-Utils"
    | "ComfyUI-Diffusers"
    | "ComfyUI-DragAnything"
    | "ComfyUI-DragNUWA"
    | "ComfyUI-Dream-Interpreter"
    | "ComfyUI-DRMN"
    | "ComfyUI-dust3r"
    | "ComfyUI-DynamiCrafter"
    | "ComfyUI-DynamiCrafterWrapper"
    | "ComfyUI-EasyAnimate"
    | "comfyui-easyapi-nodes"
    | "ComfyUI-EasyDeforum"
    | "ComfyUI-EasyOCR"
    | "ComfyUI-ELLA"
    | "ComfyUI-ELLA-wrapper"
    | "ComfyUI-Embeddings-Tools"
    | "comfyui-enhanced-save-node"
    | "Comfyui-ergouzi-Nodes"
    | "ComfyUI-ExLlama"
    | "ComfyUI-FaceChain"
    | "ComfyUI-fal-Connector"
    | "ComfyUI-Fans"
    | "ComfyUI-fastblend"
    | "comfyui-fb-utils"
    | "ComfyUI-FBCNN"
    | "ComfyUI-FishSpeech"
    | "comfyui-fitsize"
    | "ComfyUI-FLATTEN"
    | "ComfyUI-Flowty-CRM"
    | "ComfyUI-Flowty-LDSR"
    | "ComfyUI-Flowty-TripoSR"
    | "ComfyUI-FutureWarningIgnore"
    | "ComfyUI-GCP-Storage"
    | "Comfyui-Gelbooru"
    | "ComfyUI-Gemini"
    | "ComfyUI-Gemma"
    | "comfyui-geometry"
    | "ComfyUI-GlifNodes"
    | "ComfyUI-GPEN"
    | "ComfyUI-GPT_SoVITS"
    | "ComfyUI-GPT2P"
    | "ComfyUI-GPT4V-Image-Captioner"
    | "ComfyUI-graphToPrompt"
    | "ComfyUI-GTSuya-Nodes"
    | "ComfyUI-Hangover-Moondream"
    | "ComfyUI-Hangover-Nodes"
    | "ComfyUI-Helper-Nodes"
    | "ComfyUI-HF"
    | "ComfyUI-HfLoader"
    | "ComfyUI-HQ-Image-Save"
    | "ComfyUI-HyperSDXL1StepUnetScheduler (ByteDance)"
    | "ComfyUI-I2VGEN-XL"
    | "ComfyUI-IC-Light"
    | "ComfyUI-IC-Light-Native"
    | "ComfyUI-IDM-VTON [WIP]"
    | "ComfyUI-IF_AI_HFDownloaderNode"
    | "ComfyUI-IF_AI_tools"
    | "ComfyUI-IF_AI_WishperSpeechNode"
    | "ComfyUI-Image-Browsing"
    | "ComfyUI-Image-Filters"
    | "ComfyUI-Image-Matting"
    | "comfyui-Image-reward"
    | "comfyui-image-round"
    | "ComfyUI-Image-Selector"
    | "ComfyUI-Image-Tools"
    | "ComfyUI-ImageCropper"
    | "ComfyUI-IMG_Query"
    | "ComfyUI-Img2Img-Turbo"
    | "ComfyUI-Inpaint-CropAndStitch"
    | "ComfyUI-InstantID"
    | "ComfyUI-InstantIDUtils"
    | "ComfyUI-InstantMesh"
    | "ComfyUI-InversedNoise"
    | "ComfyUI-IP_LAP"
    | "ComfyUI-IPAnimate"
    | "ComfyUI-IsNiceParts"
    | "ComfyUI-J"
    | "ComfyUI-JaRue"
    | "ComfyUI-JDCN"
    | "ComfyUI-Jjk-Nodes"
    | "ComfyUI-JNodes"
    | "comfyui-job-iterator"
    | "ComfyUI-KepOpenAI"
    | "ComfyUI-kewky_tools"
    | "ComfyUI-Keyframed"
    | "Comfyui-Lama"
    | "ComfyUI-Latent-Modifiers"
    | "ComfyUI-LaVi-Bridge-Wrapper"
    | "ComfyUI-LaVIT"
    | "ComfyUI-layerdiffuse (layerdiffusion)"
    | "ComfyUI-LexTools"
    | "ComfyUI-LightGlue"
    | "ComfyUI-Live2DViewer"
    | "ComfyUI-Llama"
    | "comfyui-llm-assistant"
    | "ComfyUI-LLMs"
    | "ComfyUI-load-image-from-url"
    | "comfyui-load-image-in-seq"
    | "comfyui-local-db"
    | "ComfyUI-Logic"
    | "ComfyUI-LogicUtils"
    | "ComfyUI-Login"
    | "ComfyUI-Long-CLIP"
    | "ComfyUI-Lora-Auto-Trigger-Words"
    | "ComfyUI-LoRA-Tuner"
    | "comfyui-magic-clothing"
    | "ComfyUI-MagicAnimate"
    | "ComfyUI-MagickWand"
    | "ComfyUI-Malefish-Custom-Scripts"
    | "ComfyUI-Mana-Nodes"
    | "ComfyUI-Manager"
    | "comfyui-mask-util"
    | "ComfyUI-MaskBatchPermutations"
    | "ComfyUI-MeshMesh"
    | "Comfyui-Minio"
    | "comfyui-mixlab-nodes"
    | "ComfyUI-mnemic-nodes"
    | "ComfyUI-Mobile"
    | "ComfyUI-Model-Manager"
    | "ComfyUI-ModelDownloader"
    | "ComfyUI-moondream"
    | "ComfyUI-Moore-AnimateAnyone"
    | "ComfyUI-Motion-Vector-Extractor"
    | "ComfyUI-MotionCtrl"
    | "ComfyUI-MotionCtrl-SVD"
    | "Comfyui-MusePose"
    | "ComfyUI-MuseTalk"
    | "ComfyUI-MuseTalk_FSH"
    | "ComfyUI-MuseTalkUtils"
    | "ComfyUI-MuseV"
    | "ComfyUI-MX-post-processing-nodes"
    | "ComfyUI-N-Nodes"
    | "ComfyUI-N-Sidebar"
    | "comfyui-NDI"
    | "ComfyUI-NegiTools"
    | "ComfyUI-nevysha-top-menu"
    | "ComfyUI-ngrok"
    | "comfyui-nodes-docs"
    | "ComfyUI-nodes-hnmr"
    | "ComfyUi-NoodleWebcam"
    | "ComfyUI-Notifications"
    | "ComfyUI-Novakid"
    | "ComfyUI-NSFW-Detection"
    | "comfyUI-nsfw-detection"
    | "ComfyUI-off-suite"
    | "ComfyUI-Ollama-Describer"
    | "ComfyUi-Ollama-YN"
    | "comfyui-oms-diffusion"
    | "ComfyUI-Open-Sora"
    | "ComfyUI-Open-Sora-Plan"
    | "ComfyUI-openpose-editor"
    | "ComfyUI-Openpose-Editor-Plus"
    | "ComfyUI-OtherVAEs"
    | "ComfyUI-ownimage"
    | "comfyui-paint"
    | "ComfyUI-Paint-by-Example"
    | "ComfyUI-Panda3d"
    | "ComfyUI-Path-Helper"
    | "ComfyUI-Photopea"
    | "comfyui-photoshop"
    | "ComfyUI-PixArt-alpha-Diffusers"
    | "comfyui-pixel"
    | "ComfyUI-PixelOE"
    | "comfyui-popup_preview"
    | "ComfyUI-Portrait-Maker"
    | "comfyui-portrait-master"
    | "comfyui-portrait-master-zh-cn"
    | "ComfyUI-post-processing-nodes"
    | "ComfyUI-Prediction"
    | "ComfyUI-Prediction-Boost"
    | "comfyui-previewlatent"
    | "ComfyUI-Prompt-Combinator"
    | "comfyui-prompt-composer"
    | "ComfyUI-Prompt-Expansion"
    | "comfyui-prompt-format"
    | "ComfyUI-Prompt-MZ"
    | "ComfyUI-Prompt-Preview"
    | "ComfyUI-promptLAB"
    | "ComfyUI-PromptOrganizer"
    | "ComfyUI-PromptUtilities"
    | "ComfyUI-Pronodes"
    | "ComfyUI-ProPost"
    | "comfyui-psd2png"
    | "ComfyUI-Pymunk"
    | "ComfyUI-Q-Align"
    | "ComfyUI-Qais-Helper"
    | "ComfyUI-Qwen-VL-API"
    | "ComfyUI-RAFT"
    | "comfyui-random-node"
    | "ComfyUI-RAVE"
    | "ComfyUI-RAVE Attention"
    | "ComfyUI-RawSaver"
    | "ComfyUI-RefSampling"
    | "comfyui-remote-tools"
    | "ComfyUI-Remover"
    | "ComfyUI-RenderRiftNodes"
    | "ComfyUI-RequestPoster"
    | "comfyui-ricklove"
    | "ComfyUI-RunRunRun"
    | "ComfyUI-RUS localization"
    | "ComfyUI-RVC"
    | "ComfyUI-safety-checker"
    | "Comfyui-SAL-VTON"
    | "ComfyUI-sampler-lcm-alternative"
    | "ComfyUI-Saveaswebp"
    | "ComfyUI-SaveAVIF"
    | "ComfyUI-SaveImageWithMetaData"
    | "ComfyUI-SaveQueues"
    | "ComfyUI-ScenarioPrompt"
    | "ComfyUI-SceneGenerator"
    | "ComfyUI-SDXL-EmptyLatentImage"
    | "ComfyUI-seam-carving"
    | "comfyui-selector"
    | "ComfyUI-send-Eagle(slim)"
    | "ComfyUI-ShadertoyGL"
    | "ComfyUI-Shinsplat"
    | "ComfyUI-SimDA"
    | "ComfyUI-Simple-Aspect-Ratio"
    | "ComfyUI-SimpleCounter"
    | "ComfyUI-Simply-Nodes"
    | "ComfyUI-SizeFromArray"
    | "ComfyUI-SizeFromPresets"
    | "ComfyUI-sonar"
    | "ComfyUI-speech-dataset-toolkit"
    | "ComfyUI-stable-wildcards"
    | "ComfyUI-Static-Primitives"
    | "ComfyUI-Stereopsis"
    | "ComfyUI-Sticker"
    | "ComfyUI-string-util"
    | "ComfyUI-StyleGan"
    | "ComfyUI-styles-all"
    | "ComfyUI-StylizePhoto-MZ"
    | "ComfyUI-SubjectStyle-CSV"
    | "ComfyUI-sudo-latent-upscale"
    | "ComfyUI-SuperBeasts"
    | "ComfyUI-SUPIR"
    | "ComfyUI-SVD"
    | "ComfyUI-SVD-ZHO (WIP)"
    | "ComfyUI-SVDResizer"
    | "ComfyUI-TacoNodes"
    | "ComfyUI-Tara-LLM-Integration"
    | "ComfyUI-TCD"
    | "ComfyUI-TCD-scheduler"
    | "ComfyUI-TeaNodes"
    | "ComfyUI-TemporaryLoader"
    | "ComfyUI-Tensor-Operations"
    | "ComfyUI-Text_Image-Composite [WIP]"
    | "ComfyUI-text-file-util"
    | "ComfyUI-TextOnSegs"
    | "ComfyUI-TextOverlay"
    | "ComfyUI-Texture-Simple"
    | "ComfyUI-TextUtils"
    | "ComfyUI-TITrain"
    | "Comfyui-Toolbox"
    | "ComfyUI-Trajectory"
    | "ComfyUI-Transceiver📡"
    | "ComfyUI-TranscriptionTools"
    | "ComfyUI-Transformers"
    | "ComfyUI-TrashNodes-DownloadHuggingface"
    | "ComfyUI-TrollSuite"
    | "ComfyUI-TTS"
    | "comfyui-ultralytics-yolo"
    | "comfyui-undistort"
    | "comfyui-upscale-by-model"
    | "ComfyUI-UVR5"
    | "ComfyUI-Vextra-Nodes"
    | "ComfyUI-Video-Editing-X-Attention"
    | "ComfyUI-Video-Matting"
    | "ComfyUI-VideoHelperSuite"
    | "ComfyUI-Vivax-Nodes"
    | "ComfyUI-Vsgan"
    | "comfyui-webcam-node"
    | "ComfyUI-WhisperX"
    | "ComfyUI-Workflow-Encrypt"
    | "ComfyUI-XTTS"
    | "comfyui-yanc"
    | "Comfyui-Yolov8-JSON"
    | "ComfyUI-Zero123-Porting"
    | "ComfyUI-ZeroShot-MTrans"
    | "ComfyUI's ControlNet Auxiliary Preprocessors"
    | "comfyui's gaffer(ComfyUI native implementation of IC-Light. )"
    | "ComfyUIInvisibleWatermark"
    | "ComfyUIJasonNode"
    | "ComfyWarp"
    | "ConCarneNode"
    | "Consistency Decoder"
    | "ControlNet Auxiliar"
    | "ControlNet-LLLite-ComfyUI"
    | "Core ML Suite for ComfyUI"
    | "Cozy Human Parser"
    | "Cozy Reference Pose Generator"
    | "Cozy Utils"
    | "CPlus_Ardenius ComfyUI Control Box"
    | "CrasH Utils"
    | "Crystools"
    | "Crystools-save"
    | "CS Transform Node for ComfyUI"
    | "cspnodes"
    | "Custom Nodes by xss"
    | "Cute Comfy"
    | "cyberdolphin"
    | "Cyclist"
    | "D2 Size Selector"
    | "D2 Steps"
    | "DarkPrompts"
    | "Deforum Nodes"
    | "demofusion-comfyui"
    | "DepthFM IN COMFYUI"
    | "Derfuu_ComfyUI_ModdedNodes"
    | "diffus3/ComfyUI-extensions"
    | "Diffusion360_ComfyUI"
    | "DiffusionLight implementation for ComfyUI"
    | "Dir Gir"
    | "Disco Diffusion"
    | "Dream Project Animation Nodes"
    | "Dream Video Batches"
    | "DynamicOversampling"
    | "DynamicPrompts Custom Nodes"
    | "DZ-FaceDetailer"
    | "Eagle PNGInfo"
    | "Eagleshadow Custom Nodes"
    | "easy-comfy-nodes"
    | "EasyCaptureNode for ComfyUI"
    | "Efficiency Nodes for ComfyUI Version 2.0+"
    | "Embedding Picker"
    | "Endless ️🌊✨ Nodes"
    | "Euler-Smea-Dyn-Sampler"
    | "Extended Image Formats for ComfyUI"
    | "Extended Save Image for ComfyUI"
    | "Extra Models for ComfyUI"
    | "ezXY scripts and nodes"
    | "Face Analysis for ComfyUI"
    | "Face Compare"
    | "Faceless Node for ComfyUI"
    | "Facerestore CF (Code Former)"
    | "FaceSwap"
    | "failfast-comfyui-extensions"
    | "fast_video_comfyui"
    | "fcSuite"
    | "Fearnworks Custom Nodes"
    | "feidorian-ComfyNodes"
    | "fexli-util-node-comfyui"
    | "FizzNodes"
    | "FreeU_Advanced"
    | "Geowizard depth and normal estimation in ComfyUI"
    | "GPU temperature protection"
    | "GR Prompt Selector"
    | "graphNavigator"
    | "Hakkun-ComfyUI-nodes"
    | "Harrlogos Prompt Builder Node"
    | "Hayo comfyui nodes"
    | "hd-nodes-comfyui"
    | "HFDownLoad Node for ComfyUI"
    | "Hiero-Nodes"
    | "hus' utils for ComfyUI"
    | "IC-Light-ComfyUI-Node"
    | "IG Interpolation Nodes"
    | "Image chooser"
    | "Image Gallery"
    | "Image loader with subfolders"
    | "Image Resize for ComfyUI"
    | "Image to Text Node"
    | "Image Uploader"
    | "image_control"
    | "Image-Captioning-in-ComfyUI"
    | "Image-vector-for-ComfyUI"
    | "Image2Halftone Node for ComfyUI"
    | "ImageProcessing"
    | "ImageReward"
    | "ImagesGrid"
    | "img2colors-comfyui-node"
    | "img2txt-comfyui-nodes"
    | "ImgProcessing_ComfyUI"
    | "InstanceDiffusion Nodes"
    | "Integrated Nodes for ComfyUI"
    | "InterpolateEverything"
    | "Isaac's Nodes"
    | "Jags_Audiotools"
    | "Jags_VectorMagic"
    | "Jovimetrix Composition Nodes"
    | "JPS Custom Nodes for ComfyUI"
    | "Kandinsky 2.2 ComfyUI Plugin"
    | "kb-comfyui-nodes"
    | "KepPromptLang"
    | "KJNodes for ComfyUI"
    | "Klinter_nodes"
    | "Knodes"
    | "komojini-comfyui-nodes"
    | "KSampler GPU"
    | "LAizypainter-Exporter-ComfyUI"
    | "Latent Consistency Model for ComfyUI"
    | "Latent Mirror node for ComfyUI"
    | "Latent-Interposer"
    | "LatentToRGB"
    | "Lazy Pony Prompter"
    | "LCM_Inpaint-Outpaint_Comfy"
    | "LCMSampler-ComfyUI"
    | "LexMSDBNodes"
    | "LiamUtil"
    | "LiamUtil (single node)"
    | "Light Gradient for ComfyUI"
    | "Lists Cartesian Product"
    | "LLM Node for ComfyUI"
    | "Load Image From Base64 URI"
    | "LoadLoraWithTags"
    | "lollms_nodes_suite"
    | "LoRA Power-Merger ComfyUI"
    | "LoRA Tag Loader for ComfyUI"
    | "Lora-Training-in-Comfy"
    | "LoraInfo"
    | "LoRTnoC-ComfyUI"
    | "m9-prompts-comfyui"
    | "m957ymj75urz/ComfyUI-Custom-Nodes"
    | "mape's helpers"
    | "Marigold depth estimation in ComfyUI"
    | "Masquerade Nodes"
    | "MBM's Music Visualizer"
    | "MergeBlockWeighted_fo_ComfyUI"
    | "mihaiiancu/Inpaint"
    | "Mikey Nodes"
    | "mm-comfyui-loopback"
    | "mm-comfyui-megamask"
    | "Mosaica"
    | "MTB Nodes"
    | "Node - Size Matcher"
    | "Node Pack mostly for manipulating strings and integers"
    | "NodeGPT"
    | "noEmbryo nodes"
    | "noise latent perlinpinpin"
    | "ntdviet/comfyui-ext"
    | "nui suite"
    | "NX_PromptStyler"
    | "One Button Prompt"
    | "OneDiff Nodes"
    | "OpenAINode"
    | "OpenPose Editor"
    | "OpenPose Keypoint Extractor"
    | "Ostris Nodes ComfyUI"
    | "Otonx's Custom Nodes"
    | "pants"
    | "Perturbed-Attention Guidance"
    | "petty-paint-comfyui-node"
    | "pfaeff-comfyui"
    | "pfg-ComfyUI"
    | "Phi-3-mini in ComfyUI"
    | "Pixelization"
    | "Plush-for-ComfyUI"
    | "Pomfy - Photoshop and ComfyUI 2-way sync"
    | "PoseKeypoint Mask"
    | "Power Noise Suite for ComfyUI"
    | "PPF_Noise_ComfyUI"
    | "Preset Dimensions"
    | "Preview Subselection Node for ComfyUI"
    | "Primere nodes for ComfyUI"
    | "primitive-types"
    | "Prompt Info"
    | "prompt-generator"
    | "PuLID_ComfyUI"
    | "pythongosssss/ComfyUI-Custom-Scripts"
    | "qq-nodes-comfyui"
    | "QRNG_Node_ComfyUI"
    | "quadmoon's ComfyUI nodes"
    | "Quality of life Suit:V2"
    | "queuetools"
    | "Ranbooru for ComfyUI"
    | "Random Size"
    | "rcsaquino/comfyui-custom-nodes"
    | "ReActor Node for ComfyUI"
    | "Recognize Anything Model (RAM) for ComfyUI"
    | "Recommended Resolution Calculator"
    | "Rembg Background Removal Node for ComfyUI"
    | "Rembg Background Removal Node for ComfyUI (Better)"
    | "ResAdapter for ComfyUI"
    | "ResolutionSelector for ComfyUI"
    | "Restart Sampling"
    | "RF Nodes"
    | "rgthree's ComfyUI Nodes"
    | "rk-comfy-nodes"
    | "RUI-Nodes"
    | "RuiquNodes for ComfyUI"
    | "Runtime44 ComfyUI Nodes"
    | "SaltAI Language Toolkit"
    | "SaltAI_LlamaIndex"
    | "SaltAI-Open-Resources"
    | "Save Image Extended for ComfyUI"
    | "Save Image Plus for ComfyUI"
    | "Save Image with Generation Metadata"
    | "Save Layers Node for ComfyUI"
    | "SaveAsScript"
    | "SaveImgPrompt"
    | "SComfyUI-Keyframe"
    | "SD Prompt Reader"
    | "SD-Advanced-Noise"
    | "SD-Latent-Upscaler"
    | "SD-PPP"
    | "SDFXBridgeForComfyUI - ComfyUI Custom Node for SDFX Integration"
    | "SDXL Auto Prompter"
    | "SDXL Prompt Styler"
    | "SDXL Prompt Styler (customized version by wolfden)"
    | "SDXL_sizing"
    | "SDXLCustomAspectRatio"
    | "SDXLResolutionPresets"
    | "Seamless tiling Node for ComfyUI"
    | "SeargeSDXL"
    | "SeeCoder [WIP]"
    | "segment anything"
    | "segment_to_mask_comfyui"
    | "select_folder_path_easy"
    | "Self-Guidance nodes"
    | "sigmas_tools_and_the_golden_scheduler"
    | "Simple Math"
    | "Simple Wildcard"
    | "simple wildcard for ComfyUI"
    | "SimpleTiles"
    | "Simswap Node for ComfyUI"
    | "Sketch2Manga"
    | "smZNodes"
    | "SpliceTools"
    | "SRL's nodes"
    | "Stability API nodes for ComfyUI"
    | "stability-ComfyUI-nodes"
    | "Stable Diffusion Dynamic Thresholding (CFG Scale Fix)"
    | "Stable-Diffusion-temperature-settings"
    | "StableCascadeResizer"
    | "StableZero123-comfyui"
    | "Steerable Motion"
    | "StyleAligned for ComfyUI"
    | "Styles CSV Loader Extension for ComfyUI"
    | "SuperPrompter Node for ComfyUI"
    | "Suplex Misc ComfyUI Nodes"
    | "Syrian Falcon Nodes"
    | "tdxh_node_comfyui"
    | "TEMP_ComfyUI-BRIA_AI-RMBG"
    | "Text to video for Stable Video Diffusion in ComfyUI"
    | "TGu Utilities"
    | "TheAlly's Custom Nodes"
    | "Tiled Diffusion & VAE for ComfyUI"
    | "Tiled sampling for ComfyUI"
    | "tiled_ksampler"
    | "Touchpad two-finger gesture support for macOS"
    | "Tracking Nodes for Videos"
    | "tri3d-comfyui-nodes"
    | "Tripo for ComfyUI"
    | "trNodes"
    | "TW-CUI-Util"
    | "UltimateSDUpscale"
    | "ULTools for ComfyUI"
    | "unwdef-nodes"
    | "Use Everywhere (UE Nodes)"
    | "Variables for Comfy UI"
    | "Variation seeds"
    | "Various ComfyUI Nodes by Type"
    | "Various custom nodes by Eden.art"
    | "Vector_Sculptor_ComfyUI"
    | "Vid2vid"
    | "Virtuoso Nodes for ComfyUI"
    | "VLM_nodes"
    | "WAS Node Suite"
    | "WAS_Extras"
    | "Wav2Lip Node for ComfyUI"
    | "Waveform Extensions"
    | "WebDev9000-Nodes"
    | "WebUI Monaco Prompt"
    | "Wildcards"
    | "wlsh_nodes"
    | "Xycuno Oobabooga"
    | "y.k.'s ComfyUI node suite"
    | "YARS: Yet Another Resolution Selector"
    | "ymc-node-suite-comfyui"
    | "zhangp365/Some Utils for ComfyUI"
    | "zhihuige-nodes-comfyui"
    | "ZSuite"
    | "Zuellni/ComfyUI-Custom-Nodes"


