// prettier-ignore
export type KnownCustomNode_Title =
    | "🐰 MarasIT Nodes"
    | "a-person-mask-generator"
    | "A8R8 ComfyUI Nodes"
    | "abg-comfyui"
    | "abracadabra-comfyui"
    | "Advanced CLIP Text Encode"
    | "Advanced Latent Control"
    | "AegisFlow Utility Nodes"
    | "AIGODLIKE-ComfyUI-Studio"
    | "AIGODLIKE-COMFYUI-TRANSLATION"
    | "AlekPet/ComfyUI_Custom_Nodes_AlekPet"
    | "alkemann nodes"
    | "Allor Plugin"
    | "Amazon Bedrock nodes for for ComfyUI"
    | "AnimateDiff"
    | "AnimateDiff Evolved"
    | "Animatediff MotionLoRA Trainer"
    | "Anime Character Segmentation node for comfyui"
    | "antrobots ComfyUI Nodepack"
    | "As_ComfyUI_CustomNodes"
    | "asagi4/comfyui-utility-nodes"
    | "ASTERR"
    | "asymmetric-tiling-comfyui"
    | "attention-couple-ComfyUI"
    | "auto nodes layout"
    | "Auto-MBW"
    | "avatar-graph-comfyui"
    | "Batch Rembg for ComfyUI"
    | "Batch-Condition-ComfyUI"
    | "BilboX's ComfyUI Custom Nodes"
    | "Bmad Nodes"
    | "braintacles-nodes"
    | "BrevImage"
    | "bsz-cui-extras"
    | "Canvas Tab"
    | "cd-tuner_negpip-ComfyUI"
    | "Character Face Swap"
    | "Chatbox Overlay node for ComfyUI"
    | "CLIP Directional Prompt Attention"
    | "CLIPSeg"
    | "Color Enhance"
    | "Comfy AI DoubTech.ai Image Sumission Node"
    | "Comfy Cloud"
    | "Comfy UI FatLabels"
    | "Comfy UI Online Loaders"
    | "Comfy UI Prompt Agent"
    | "Comfy UI QR Codes"
    | "comfy_clip_blip_node"
    | "Comfy_KepKitchenSink"
    | "Comfy_KepListStuff"
    | "Comfy_KepMatteAnything"
    | "comfy_meh"
    | "comfy_PoP"
    | "comfy-easy-grids"
    | "Comfy-LFO"
    | "comfy-mecha"
    | "comfy-nodes"
    | "Comfy-Photoshop-SD"
    | "comfy-plasma"
    | "ComfyBreakAnim"
    | "ComfyI2I"
    | "ComfyLiterals"
    | "ComfyMath"
    | "ComfyQR"
    | "ComfyQR-scanning-nodes"
    | "ComfyS3"
    | "ComfyUI - Apply LoRA Stacker with DARE"
    | "ComfyUI - Mask Bounding Box"
    | "ComfyUI - P2LDGAN Node"
    | "ComfyUI - Text Overlay Plugin"
    | "ComfyUI 3D Pose Editor"
    | "ComfyUI A1111-like Prompt Custom Node Solution"
    | "ComfyUI aichemy nodes"
    | "ComfyUI Assistant"
    | "ComfyUI Better Strings"
    | "ComfyUI Browser"
    | "ComfyUI Clear Screen"
    | "ComfyUI Cutoff"
    | "ComfyUI Deepface"
    | "ComfyUI Deploy"
    | "ComfyUI Diffusion Color Grading"
    | "ComfyUI Discopixel Nodes"
    | "ComfyUI Easy Padding"
    | "ComfyUI Easy Use"
    | "ComfyUI Essentials"
    | "ComfyUI Extra Samplers"
    | "ComfyUI fabric"
    | "ComfyUI Fictiverse Nodes"
    | "ComfyUI Floodgate"
    | "ComfyUI for InstructIR"
    | "ComfyUI Frame Interpolation"
    | "ComfyUI Frame Maker"
    | "Comfyui HiFORCE Plugin"
    | "ComfyUI Image Saver"
    | "ComfyUI Impact Pack"
    | "ComfyUI Inpaint Nodes"
    | "ComfyUI Inspire Pack"
    | "ComfyUI InstantID (Native Support)"
    | "ComfyUI InstantID Faceswapper"
    | "ComfyUI Iterative Mixing Nodes"
    | "Comfyui lama remover"
    | "ComfyUI Layer Style"
    | "ComfyUI LLaVA Captioner"
    | "ComfyUI Loopchain"
    | "ComfyUI Menu Anchor"
    | "ComfyUI MotionDiff"
    | "ComfyUI Multi-Workspace"
    | "ComfyUI Neural Network Latent Upscale"
    | "ComfyUI Nodes for External Tooling"
    | "ComfyUI Nodes for Inference.Core"
    | "ComfyUI Noise"
    | "ComfyUI Ollama"
    | "ComfyUI OOTDiffusion"
    | "ComfyUI Optical Flow"
    | "ComfyUI Pets"
    | "ComfyUI PhotoMaker (ZHO)"
    | "ComfyUI PhotoMaker Plus"
    | "ComfyUI PickScore Nodes"
    | "ComfyUI PixelArt Detector"
    | "ComfyUI PNG Metadata"
    | "ComfyUI Preset Merger"
    | "ComfyUI Profiler"
    | "ComfyUI prompt control"
    | "ComfyUI Prompt ExtraNetworks"
    | "ComfyUI Ricing"
    | "ComfyUI roop"
    | "ComfyUI SegMoE"
    | "ComfyUI Sequential Image Loader"
    | "ComfyUI Serving toolkit"
    | "ComfyUI SimpleTools Suit"
    | "ComfyUI Slothful Attention"
    | "ComfyUI Sokes Nodes"
    | "ComfyUI Stable Video Diffusion"
    | "ComfyUI String Tools"
    | "ComfyUI Substring"
    | "ComfyUI Tab Handler"
    | "ComfyUI WD 1.4 Tagger"
    | "Comfyui Webcam capture node"
    | "ComfyUI Whisper"
    | "ComfyUI Workspace Manager - Comfyspace"
    | "ComfyUI Yolov8"
    | "ComfyUI YoloWorld-EfficientSAM"
    | "comfyui_ab_sampler"
    | "ComfyUI_API_Manager"
    | "ComfyUI_aspect_ratios"
    | "comfyui_auto_danbooru"
    | "ComfyUI_BadgerTools"
    | "ComfyUI_Blender_Texdiff"
    | "ComfyUI_CartoonSegmentation"
    | "ComfyUI_ColorMod"
    | "ComfyUI_Comfyroll_CustomNodes"
    | "ComfyUI_DiT [WIP]"
    | "ComfyUI_Dragos_Nodes"
    | "comfyui_DSP_imagehelpers"
    | "ComfyUI_experiments"
    | "comfyui_face_parsing"
    | "comfyui_facetools"
    | "ComfyUI_FastVAEDecorder_SDXL"
    | "ComfyUI_Fill-Nodes"
    | "ComfyUI_Fooocus_KSampler"
    | "ComfyUI_GLM4Node"
    | "ComfyUI_GMIC"
    | "ComfyUI_GradientDeepShrink"
    | "ComfyUI_Ib_CustomNodes"
    | "Comfyui_image2prompt"
    | "comfyui_io_helpers"
    | "ComfyUI_IPAdapter_plus"
    | "ComfyUI_Jags_Audiotools"
    | "ComfyUI_Jags_VectorMagic"
    | "Comfyui_joytag"
    | "ComfyUI_Mexx_Poster"
    | "ComfyUI_Mexx_Styler"
    | "ComfyUI_MileHighStyler"
    | "ComfyUI_Mira"
    | "ComfyUI_ModelScopeT2V"
    | "ComfyUI_mozman_nodes"
    | "ComfyUI_MSSpeech_TTS"
    | "ComfyUI_NAIDGenerator"
    | "ComfyUI_NetDist"
    | "ComfyUI_Nimbus-Pack"
    | "comfyUI_Nodes_nicolai256"
    | "ComfyUI_NoxinNodes"
    | "ComfyUI_OOTDiffusion_CXH"
    | "ComfyUI_PerpWeight"
    | "ComfyUI_Pilgram"
    | "comfyui_quilting"
    | "ComfyUI_RErouter_CustomNodes"
    | "ComfyUI_rotate_image"
    | "ComfyUI_SDXL_DreamBooth_LoRA_CustomNodes"
    | "ComfyUI_Seg_VITON"
    | "comfyui_segformer_b2_clothes"
    | "ComfyUI_Segment_Mask"
    | "ComfyUI_StreamDiffusion"
    | "ComfyUI_Strimmlarns_aesthetic_score"
    | "ComfyUi_String_Function_Tree"
    | "ComfyUI_TextAssets"
    | "ComfyUI_toyxyz_test_nodes"
    | "ComfyUI_TravelSuite"
    | "comfyui_visual_anagram"
    | "comfyui_wfc_like"
    | "ComfyUI_WordCloud"
    | "ComfyUI_zfkun"
    | "ComfyUI-0246"
    | "ComfyUI-3D-Pack"
    | "ComfyUI-Advanced-ControlNet"
    | "ComfyUI-AIT"
    | "ComfyUI-Anchors"
    | "ComfyUI-AnimateAnyone-Evolved"
    | "ComfyUI-AnimateAnyone-reproduction"
    | "comfyui-art-venture"
    | "ComfyUI-ArtGallery"
    | "ComfyUI-AudioReactive"
    | "ComfyUI-AudioReactor"
    | "ComfyUI-AudioScheduler"
    | "ComfyUI-AutomaticCFG"
    | "ComfyUI-Background-Replacement"
    | "ComfyUI-bleh"
    | "ComfyUI-Bmad-DirtyUndoRedo"
    | "ComfyUI-CADS"
    | "ComfyUI-Calculation"
    | "ComfyUI-CascadeResolutions"
    | "ComfyUI-Catcat"
    | "ComfyUI-CCSR"
    | "ComfyUI-Chat-GPT-Integration"
    | "ComfyUI-Chibi-Nodes"
    | "comfyui-clip-with-break"
    | "ComfyUI-ClipScore-Nodes"
    | "ComfyUI-ComfyCouple"
    | "ComfyUI-ComfyRun"
    | "ComfyUI-ComfyWorkflows"
    | "ComfyUI-Coziness"
    | "ComfyUI-Cre8it-Nodes"
    | "ComfyUI-CSV-Loader"
    | "ComfyUI-DareMerge"
    | "ComfyUI-Dart"
    | "ComfyUI-DDColor"
    | "ComfyUI-deepcache"
    | "ComfyUI-Depth-Visualization"
    | "ComfyUI-Diffusers"
    | "ComfyUI-DragNUWA"
    | "ComfyUI-Dream-Interpreter"
    | "ComfyUI-dust3r"
    | "ComfyUI-DynamiCrafter"
    | "comfyui-easyapi-nodes"
    | "comfyui-enhanced-save-node"
    | "Comfyui-ergouzi-Nodes"
    | "ComfyUI-ExLlama"
    | "ComfyUI-FaceChain"
    | "Comfyui-FaceCompare"
    | "ComfyUI-Fans"
    | "ComfyUI-fastblend"
    | "ComfyUI-FBCNN"
    | "comfyui-fitsize"
    | "ComfyUI-Flowty-LDSR"
    | "ComfyUI-Flowty-TripoSR"
    | "ComfyUI-Gemini"
    | "ComfyUI-Gemma"
    | "comfyui-geometry"
    | "ComfyUI-GlifNodes"
    | "ComfyUI-GPT2P"
    | "ComfyUI-GPT4V-Image-Captioner"
    | "ComfyUI-GTSuya-Nodes"
    | "ComfyUI-Hangover-Moondream"
    | "ComfyUI-Hangover-Nodes"
    | "ComfyUI-HF"
    | "ComfyUI-Hiero-Nodes"
    | "ComfyUI-HQ-Image-Save"
    | "ComfyUI-I2VGEN-XL"
    | "ComfyUI-Image-Browsing"
    | "ComfyUI-Image-Filters"
    | "ComfyUI-Image-Matting"
    | "comfyui-image-round"
    | "ComfyUI-Image-Selector"
    | "ComfyUI-Image-Tools"
    | "ComfyUI-InstantID"
    | "ComfyUI-IPAnimate"
    | "ComfyUI-JaRue"
    | "ComfyUI-Jjk-Nodes"
    | "ComfyUI-JNodes"
    | "comfyui-job-iterator"
    | "ComfyUI-KepOpenAI"
    | "ComfyUI-Keyframed"
    | "Comfyui-Lama"
    | "ComfyUI-Latent-Modifiers"
    | "ComfyUI-layerdiffusion"
    | "ComfyUI-LexTools"
    | "ComfyUI-LightGlue"
    | "ComfyUI-Llama"
    | "comfyui-llm-assistant"
    | "ComfyUI-LLMs"
    | "ComfyUI-Logic"
    | "ComfyUI-LogicUtils"
    | "ComfyUI-Lora-Auto-Trigger-Words"
    | "ComfyUI-MagicAnimate"
    | "ComfyUI-Malefish-Custom-Scripts"
    | "ComfyUI-Manager"
    | "comfyui-mask-util"
    | "ComfyUI-MeshMesh"
    | "Comfyui-Minio"
    | "comfyui-mixlab-nodes"
    | "ComfyUI-mnemic-nodes"
    | "ComfyUI-Model-Manager"
    | "ComfyUI-ModelDownloader"
    | "ComfyUI-moondream"
    | "ComfyUI-Moore-AnimateAnyone"
    | "ComfyUI-Motion-Vector-Extractor"
    | "ComfyUI-MotionCtrl"
    | "ComfyUI-MotionCtrl-SVD"
    | "ComfyUI-N-Nodes"
    | "comfyui-NDI"
    | "ComfyUI-NegiTools"
    | "ComfyUI-ngrok"
    | "ComfyUI-nodes-hnmr"
    | "ComfyUi-NoodleWebcam"
    | "ComfyUI-NSFW-Detection"
    | "ComfyUI-off-suite"
    | "ComfyUI-Openpose-Editor-Plus"
    | "ComfyUI-OtherVAEs"
    | "ComfyUI-ownimage"
    | "ComfyUI-Paint-by-Example"
    | "ComfyUI-Panda3d"
    | "ComfyUI-Path-Helper"
    | "comfyui-photoshop"
    | "ComfyUI-PixArt-alpha-Diffusers"
    | "comfyui-popup_preview"
    | "ComfyUI-Portrait-Maker"
    | "comfyui-portrait-master"
    | "comfyui-portrait-master-zh-cn"
    | "ComfyUI-post-processing-nodes"
    | "ComfyUI-Prediction"
    | "comfyui-previewlatent"
    | "comfyui-prompt-composer"
    | "ComfyUI-Prompt-Expansion"
    | "comfyui-prompt-format"
    | "ComfyUI-Prompt-Preview"
    | "comfyui-prompt-reader-node"
    | "ComfyUI-PromptUtilities"
    | "ComfyUI-Pronodes"
    | "ComfyUI-ProPost"
    | "comfyui-psd2png"
    | "ComfyUI-Pymunk"
    | "ComfyUI-Q-Align"
    | "ComfyUI-Qais-Helper"
    | "ComfyUI-Qwen-VL-API"
    | "ComfyUI-RAFT"
    | "ComfyUI-RandomSize"
    | "ComfyUI-RAVE"
    | "ComfyUI-RawSaver"
    | "ComfyUI-Remover"
    | "ComfyUI-RenderRiftNodes"
    | "comfyui-ricklove"
    | "ComfyUI-safety-checker"
    | "ComfyUI-sampler-lcm-alternative"
    | "ComfyUI-Saveaswebp"
    | "ComfyUI-SaveAVIF"
    | "ComfyUI-SaveImageWithMetaData"
    | "ComfyUI-SaveQueues"
    | "ComfyUI-ScenarioPrompt"
    | "ComfyUI-SDXL-EmptyLatentImage"
    | "ComfyUI-seam-carving"
    | "ComfyUI-send-Eagle(slim)"
    | "ComfyUI-Simple-Aspect-Ratio"
    | "ComfyUI-SizeFromPresets"
    | "ComfyUI-sonar"
    | "ComfyUI-stable-wildcards"
    | "ComfyUI-Static-Primitives"
    | "ComfyUI-Stereopsis"
    | "ComfyUI-styles-all"
    | "ComfyUI-SubjectStyle-CSV"
    | "ComfyUI-sudo-latent-upscale"
    | "ComfyUI-SVD"
    | "ComfyUI-SVD-ZHO (WIP)"
    | "ComfyUI-SVDResizer"
    | "ComfyUI-TacoNodes"
    | "ComfyUI-TCD-scheduler"
    | "ComfyUI-TeaNodes"
    | "ComfyUI-TemporaryLoader"
    | "ComfyUI-Tensor-Operations"
    | "ComfyUI-Text_Image-Composite [WIP]"
    | "ComfyUI-TextOnSegs"
    | "ComfyUI-TextOverlay"
    | "ComfyUI-TextUtils"
    | "comfyUI-tool-2lab"
    | "Comfyui-Toolbox"
    | "ComfyUI-Transformers"
    | "ComfyUI-TrashNodes-DownloadHuggingface"
    | "ComfyUI-TrollSuite"
    | "ComfyUI-TTS"
    | "comfyui-ultralytics-yolo"
    | "comfyui-upscale-by-model"
    | "ComfyUI-Vextra-Nodes"
    | "ComfyUI-Video-Matting"
    | "ComfyUI-VideoHelperSuite"
    | "ComfyUI-Vivax-Nodes"
    | "ComfyUI-Vsgan"
    | "comfyui-webcam-node"
    | "comfyui-xin-nodes"
    | "comfyui-yanc"
    | "Comfyui-Yolov8-JSON"
    | "ComfyUI's ControlNet Auxiliary Preprocessors"
    | "ComfyUIInvisibleWatermark"
    | "ComfyUIJasonNode"
    | "ComfyWarp"
    | "ConCarneNode"
    | "Consistency Decoder"
    | "ControlNet-LLLite-ComfyUI"
    | "Core ML Suite for ComfyUI"
    | "Cozy Human Parser"
    | "CrasH Utils"
    | "Crystools"
    | "Crystools-save"
    | "cspnodes"
    | "Custom Nodes by xss"
    | "Cute Comfy"
    | "cyberdolphin"
    | "Cyclist"
    | "DarkPrompts"
    | "Deforum Nodes"
    | "demofusion-comfyui"
    | "Derfuu_ComfyUI_ModdedNodes"
    | "diffus3/ComfyUI-extensions"
    | "Dir Gir"
    | "Disco Diffusion"
    | "Dream Project Animation Nodes"
    | "Dream Video Batches"
    | "DynamicPrompts Custom Nodes"
    | "DZ-FaceDetailer"
    | "Eagle PNGInfo"
    | "easy-comfy-nodes"
    | "EasyCaptureNode for ComfyUI"
    | "eden_comfy_pipelines"
    | "Efficiency Nodes for ComfyUI Version 2.0+"
    | "Embedding Picker"
    | "Endless ️🌊✨ Nodes"
    | "Extended Save Image for ComfyUI"
    | "Extra Models for ComfyUI"
    | "ezXY scripts and nodes"
    | "Face Analysis for ComfyUI"
    | "Facerestore CF (Code Former)"
    | "FaceSwap"
    | "failfast-comfyui-extensions"
    | "fcSuite"
    | "Fearnworks Custom Nodes"
    | "feidorian-ComfyNodes"
    | "fexli-util-node-comfyui"
    | "FizzNodes"
    | "FreeU_Advanced"
    | "GPU temperature protection"
    | "graphNavigator"
    | "Hakkun-ComfyUI-nodes"
    | "Harronode"
    | "Hayo comfyui nodes"
    | "hd-nodes-comfyui"
    | "hus' utils for ComfyUI"
    | "idpark_custom_node"
    | "IG Interpolation Nodes"
    | "Image chooser"
    | "Image Gallery"
    | "Image loader with subfolders"
    | "Image Resize for ComfyUI"
    | "Image to Text Node"
    | "image_control"
    | "Image-Captioning-in-ComfyUI"
    | "Image2Halftone Node for ComfyUI"
    | "ImageProcessing"
    | "ImageReward"
    | "ImagesGrid"
    | "ImageTextOverlay Node for ComfyUI"
    | "InstanceDiffusion Nodes"
    | "InstaSwap Face Swap Node for ComfyUI"
    | "Integrated Nodes for ComfyUI"
    | "InterpolateEverything"
    | "Jovimetrix Composition Nodes"
    | "JPS Custom Nodes for ComfyUI"
    | "kb-comfyui-nodes"
    | "KepPromptLang"
    | "KJNodes for ComfyUI"
    | "Klinter_nodes"
    | "Knodes"
    | "komojini-comfyui-nodes"
    | "KSampler GPU"
    | "LAizypainter-Exporter-ComfyUI"
    | "LaMa Preprocessor [WIP]"
    | "Latent Consistency Model for ComfyUI"
    | "Latent Mirror node for ComfyUI"
    | "Latent-Interposer"
    | "LatentToRGB"
    | "Lazy Pony Prompter"
    | "LCM_Inpaint-Outpaint_Comfy"
    | "LCMSampler-ComfyUI"
    | "LexMSDBNodes"
    | "LiamUtil"
    | "Lists Cartesian Product"
    | "Load Image From Base64 URI"
    | "LoadLoraWithTags"
    | "LoRA Tag Loader for ComfyUI"
    | "LoRA-Merger-ComfyUI"
    | "Lora-Training-in-Comfy"
    | "LoraInfo"
    | "LoRTnoC-ComfyUI"
    | "m957ymj75urz/ComfyUI-Custom-Nodes"
    | "mape's ComfyUI Helpers"
    | "Marigold depth estimation in ComfyUI"
    | "Masquerade Nodes"
    | "MergeBlockWeighted_fo_ComfyUI"
    | "mihaiiancu/Inpaint"
    | "Mikey Nodes"
    | "mm-comfyui-loopback"
    | "mm-comfyui-megamask"
    | "MTB Nodes"
    | "NestedNodeBuilder"
    | "NodeGPT"
    | "noEmbryo nodes"
    | "noise latent perlinpinpin"
    | "ntdviet/comfyui-ext"
    | "nui suite"
    | "NX_PromptStyler"
    | "One Button Prompt"
    | "OneDiff Nodes"
    | "OpenAINode"
    | "OpenPose Editor"
    | "OpenPose Keypoint Extractor"
    | "Ostris Nodes ComfyUI"
    | "Otonx's Custom Nodes"
    | "pants"
    | "PerpPrompt-for-ComfyUI"
    | "pfaeff-comfyui"
    | "pfg-ComfyUI"
    | "Pixelization"
    | "Plush-for-ComfyUI"
    | "Pomfy - Photoshop and ComfyUI 2-way sync"
    | "Power Noise Suite for ComfyUI"
    | "PPF_Noise_ComfyUI"
    | "Preset Dimensions"
    | "Preview Subselection Node for ComfyUI"
    | "Primere nodes for ComfyUI"
    | "primitive-types"
    | "Prompt Info"
    | "prompt-generator"
    | "pythongosssss/ComfyUI-Custom-Scripts"
    | "qq-nodes-comfyui"
    | "QRNG_Node_ComfyUI"
    | "Quality of life Suit:V2"
    | "queuetools"
    | "Ranbooru for ComfyUI"
    | "rcsaquino/comfyui-custom-nodes"
    | "ReActor Node for ComfyUI"
    | "Recommended Resolution Calculator"
    | "Rembg Background Removal Node for ComfyUI"
    | "ResolutionSelector for ComfyUI"
    | "Restart Sampling"
    | "RF Nodes"
    | "rgthree's ComfyUI Nodes"
    | "rk-comfy-nodes"
    | "RUI-Nodes"
    | "SaltAI-Open-Resources"
    | "Save Image Extended for ComfyUI"
    | "Save Image with Generation Metadata"
    | "SaveAsScript"
    | "SaveImgPrompt"
    | "SComfyUI-Keyframe"
    | "SD-Advanced-Noise"
    | "SD-Latent-Upscaler"
    | "SDXL Auto Prompter"
    | "SDXL Prompt Styler"
    | "SDXL Prompt Styler (customized version by wolfden)"
    | "SDXL_sizing"
    | "SDXLCustomAspectRatio"
    | "SDXLResolutionPresets"
    | "Seamless tiling Node for ComfyUI"
    | "SeargeSDXL"
    | "SeeCoder [WIP]"
    | "segment anything"
    | "segment_to_mask_comfyui"
    | "select_folder_path_easy"
    | "sigmas_tools_and_the_golden_scheduler"
    | "Simple Math"
    | "Simple Wildcard"
    | "simple wildcard for ComfyUI"
    | "SimpleTiles"
    | "smZNodes"
    | "SpliceTools"
    | "SRL's nodes"
    | "stability-ComfyUI-nodes"
    | "Stable Diffusion Dynamic Thresholding (CFG Scale Fix)"
    | "StableCascadeResizer"
    | "StableZero123-comfyui"
    | "Steerable Motion"
    | "StyleAligned for ComfyUI"
    | "Styles CSV Loader Extension for ComfyUI"
    | "Syrian Falcon Nodes"
    | "tdxh_node_comfyui"
    | "TEMP_ComfyUI-BRIA_AI-RMBG"
    | "Text to video for Stable Video Diffusion in ComfyUI"
    | "TGu Utilities"
    | "TheAlly's Custom Nodes"
    | "Tiled Diffusion & VAE for ComfyUI"
    | "Tiled sampling for ComfyUI"
    | "tiled_ksampler"
    | "TiledIPAdapter"
    | "tinyterraNodes"
    | "Touchpad two-finger gesture support for macOS"
    | "Tracking Nodes for Videos"
    | "tri3d-comfyui-nodes"
    | "trNodes"
    | "UltimateSDUpscale"
    | "ULTools for ComfyUI"
    | "Use Everywhere (UE Nodes)"
    | "Variables for Comfy UI"
    | "Variation seeds"
    | "Various ComfyUI Nodes by Type"
    | "Vid2vid"
    | "Visual Area Conditioning / Latent composition"
    | "VLM_nodes"
    | "WAS Node Suite"
    | "WAS_Extras"
    | "Waveform Extensions"
    | "WebDev9000-Nodes"
    | "WebUI Monaco Prompt"
    | "Wildcards"
    | "wlsh_nodes"
    | "y.k.'s ComfyUI node suite"
    | "YARS: Yet Another Resolution Selector"
    | "ymc-node-suite-comfyui"
    | "zhihuige-nodes-comfyui"
    | "ZSuite"
    | "Zuellni/ComfyUI-Custom-Nodes"


