// This file was generated by lezer-generator. You probably shouldn't edit it.
// @ts-nocheck
// eslint-disable
import { LRParser } from '@lezer/lr'

const spec_Identifier = {__proto__:null,embedding:70, artist:74}
export const parser = LRParser.deserialize({
  version: 14,
  states: "&rQVQPOOOVQPO'#C^OVQPO'#CaO!QQPO'#CeO!]QPO'#ChO!bQPO'#CiO!gQPO'#CkOOQO'#Ct'#CtOOQO'#Cp'#CpQVQPOOO!oQPO'#CbO!oQPO'#CgO!wQPO'#C_O#UQPO,58xO#^QPO,58{O#cQPO,59POOQO'#DQ'#DQO#hQPO,59PO!oQPO,59SO#mQPO,59TOOQO'#Cl'#ClOOQO,59V,59VOOQO-E6n-E6nO#uQPO,58|O#}QPO,59ROOQO1G.d1G.dO%XQQO1G.dOOQO1G.g1G.gOOQO1G.k1G.kO#cQPO1G.kOOQO1G.n1G.nOOQO'#Cj'#CjOOQO1G.o1G.oOOQO1G.h1G.hO%^QQO1G.hOOQO1G.m1G.mO%cQPO7+$OOOQO7+$V7+$VO%hQQO7+$SOOQO<<Gj<<GjOOQO<<Gn<<GnO%pQQO<<GnO%uQPOAN=YOOQOG22tG22t",
  stateData: "&P~OgOS~OVVOWVOaVObVOcVOiPOlQOnYOqROrZOsSOuTOvUO~OV`OW`OY_O~OjbO~OjcO~OVdOWdO~OV`OW`O~OjRXkRXmRX~PVOjjOkiO~OmkO~OlQO~OYmO~OVoOWoO~OjrOpqO~OYsOVZaWZaaZabZacZaeZaiZalZanZaqZarZasZauZavZajZakZamZa~OStO~OSvO~OkwO~OoyOpxO~OSzO~Op{O~OcbVb~",
  goto: "#WuPPv}P!TvPPvPvvv!bv!ePPP!hPPP!sPPPPPPPPPPP!zZVOPQX[Q]PR^QYVOPQX[Ql_RumRpcReUQXOS[PQTfX[ZWOPQX[QaRQgYQhZRnb",
  nodeNames: "⚠ Prompt WeightedExpression Content Number Permutations Lora Identifier String Choice Index Wildcard Embedding Artist ArtistName Tag TagName Separator Break Comment",
  maxTerm: 38,
  nodeProps: [
    ["group", -13,2,5,6,7,8,9,11,12,13,15,17,18,19,"Expression"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "-S~RpX^#Vpq#Vrs#zuv$ixy$nyz$s|}$x}!O%P!O!P&V!P!Q%k!Q![&V![!]&s!]!^&x!^!_'a!`!a(U!a!b(Z!c!}%k!}#O(h#R#S%k#T#U%k#U#V)i#V#o%k#o#p,x#q#r,}#y#z#V$f$g#V#BY#BZ#V$IS$I_#V$I|$JO#V$JT$JU#V$KV$KW#V&FU&FV#V~#[Yg~X^#Vpq#V#y#z#V$f$g#V#BY#BZ#V$IS$I_#V$I|$JO#V$JT$JU#V$KV$KW#V&FU&FV#V~#}TOr#zrs$^s;'S#z;'S;=`$c<%lO#z~$cOW~~$fP;=`<%l#z~$nOv~~$sOi~~$xOk~R%POoQaPR%UVVP}!O%k!O!P&V!P!Q%k!Q![&V!c!}%k#R#S%k#T#o%kP%pVVP}!O%k!O!P%k!P!Q%k!Q![%k!c!}%k#R#S%k#T#o%kR&^VSQVP}!O%k!O!P&V!P!Q%k!Q![&V!c!}%k#R#S%k#T#o%k~&xOj~~&}Sc~OY&xZ;'S&x;'S;=`'Z<%lO&x~'^P;=`<%l&x~'dP#`#a'g~'jP#c#d'm~'pP#f#g's~'vP#T#U'y~'|P![!](P~(UOn~~(ZOp~~(`Pr~!`!a(c~(hOq~~(kS}!O(w!Q![)T!a!b)T#R#S)T~(zR!Q![)T!a!b)T#R#S)T~)WS!Q![)T!a!b)T#P#Q)d#R#S)T~)iOY~~)nXVP}!O%k!O!P%k!P!Q%k!Q![%k!c!}%k#R#S%k#T#f%k#f#g*Z#g#o%k~*`XVP}!O%k!O!P%k!P!Q%k!Q![%k!c!}%k#R#S%k#T#X%k#X#Y*{#Y#o%k~+QWVP}!O%k!O!P%k!P!Q%k!Q![%k!c!}%k#R#S%k#T#U+j#U#o%k~+oXVP}!O%k!O!P%k!P!Q%k!Q![%k!c!}%k#R#S%k#T#_%k#_#`,[#`#o%k~,cVb~VP}!O%k!O!P%k!P!Q%k!Q![%k!c!}%k#R#S%k#T#o%k~,}Ol~~-SOm~",
  tokenizers: [0, 1],
  topRules: {"Prompt":[0,1]},
  specialized: [{term: 7, get: (value): any => spec_Identifier[value] || -1}],
  tokenPrec: 226
})
