// eslint-disable
// @ts-nocheck
// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from '@lezer/lr'

const spec_Identifier = {__proto__:null,embedding:72, artist:76}
export const parser = LRParser.deserialize({
  version: 14,
  states: "&lQVQPOOOVQPO'#C^OVQPO'#CaO!QQPO'#CeO!YQPO'#ChO!_QPO'#CiO!dQPO'#CkOOQO'#Cu'#CuOOQO'#Cp'#CpQVQPOOO!lQPO'#CbO!lQPO'#CgO!tQPO'#C_O#RQPO,58xO#ZQPO,58{OOQO'#Cf'#CfOOQO'#Cq'#CqO#`QPO,59PO!lQPO,59SO#kQPO,59TOOQO'#Cl'#ClOOQO,59V,59VOOQO-E6n-E6nOOQO'#DR'#DRO#sQPO,58|OOQO,59R,59ROOQO1G.d1G.dO#{QQO1G.dOOQO1G.g1G.gOOQO-E6o-E6oOOQO1G.k1G.kOOQO1G.n1G.nOOQO'#Cj'#CjOOQO1G.o1G.oOOQO1G.h1G.hO$QQQO1G.hO$VQPO7+$OO$[QQO7+$SOOQO<<Gj<<GjOOQO<<Gn<<GnO$dQQO<<GnO$iQPOAN=YOOQOG22tG22t",
  stateData: "$s~OhOS~OVVOWVOaVObVOcVOjPOmQOoYOrROsZOtSOvTOwUO~OV_OW_O~OkbO~OkcO~OVdOWdO~OVgOWgO~OkRXlRXnRX~PVOkkOljO~OnlO~OV_OW_OqnO~OVpOWpO~OksOqrO~OStO~OSuO~OlvO~OpxOqwO~OSyO~OqzO~OcbVb~",
  goto: "#RvPPw!OPwwPPw!Uwww!Yw!]PPP!`!kPPP!qPPPPPPPPPPP!xZVOPQX[Q]PR^QT`RaRqcReUQXOS[PQTfX[QaRRmaZWOPQX[QhYQiZRob",
  nodeNames: "⚠ Prompt WeightedExpression Content Number Permutations Lora Identifier String Choice ChoiceEntry Wildcard Embedding Artist ArtistName Tag TagName Separator Break Comment",
  maxTerm: 39,
  nodeProps: [
    ["group", -13,2,5,6,7,8,9,11,12,13,15,17,18,19,"Expression"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: ",t~RoX^#Spq#Srs#wuv$fxy$kyz$p|}$u}!O$|!O!P&S!P!Q%h!Q![&S![!]&p!]!^&u!^!_'^!`!a)P!a!b)U!c!}%h#R#S%h#T#U%h#U#V)Z#V#o%h#o#p,j#q#r,o#y#z#S$f$g#S#BY#BZ#S$IS$I_#S$I|$JO#S$JT$JU#S$KV$KW#S&FU&FV#S~#XYh~X^#Spq#S#y#z#S$f$g#S#BY#BZ#S$IS$I_#S$I|$JO#S$JT$JU#S$KV$KW#S&FU&FV#S~#zTOr#wrs$Zs;'S#w;'S;=`$`<%lO#w~$`OW~~$cP;=`<%l#w~$kOw~~$pOj~~$uOl~R$|OpQaPR%RVVP}!O%h!O!P&S!P!Q%h!Q![&S!c!}%h#R#S%h#T#o%hP%mVVP}!O%h!O!P%h!P!Q%h!Q![%h!c!}%h#R#S%h#T#o%hR&ZVSQVP}!O%h!O!P&S!P!Q%h!Q![&S!c!}%h#R#S%h#T#o%h~&uOk~~&zSc~OY&uZ;'S&u;'S;=`'W<%lO&u~'ZP;=`<%l&u~'aQ#V#W'g#`#a(b~'jP#[#]'m~'pP#c#d's~'vP#]#^'y~'|P#V#W(P~(SP#X#Y(V~(YP![!](]~(bOr~~(eP#c#d(h~(kP#f#g(n~(qP#T#U(t~(wP![!](z~)POo~~)UOq~~)ZOs~~)`XVP}!O%h!O!P%h!P!Q%h!Q![%h!c!}%h#R#S%h#T#f%h#f#g){#g#o%h~*QXVP}!O%h!O!P%h!P!Q%h!Q![%h!c!}%h#R#S%h#T#X%h#X#Y*m#Y#o%h~*rWVP}!O%h!O!P%h!P!Q%h!Q![%h!c!}%h#R#S%h#T#U+[#U#o%h~+aXVP}!O%h!O!P%h!P!Q%h!Q![%h!c!}%h#R#S%h#T#_%h#_#`+|#`#o%h~,TVb~VP}!O%h!O!P%h!P!Q%h!Q![%h!c!}%h#R#S%h#T#o%h~,oOm~~,tOn~",
  tokenizers: [0, 1],
  topRules: {"Prompt":[0,1]},
  specialized: [{term: 7, get: (value): any => spec_Identifier[value] || -1}],
  tokenPrec: 168
})
