// @ts-nocheck
// eslint-disable
// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from '@lezer/lr'

const spec_Identifier = {__proto__:null,embedding:74, artist:78}
export const parser = LRParser.deserialize({
  version: 14,
  states: "&xQVQPOOOVQPO'#C^OVQPO'#CaO!QQPO'#CgO!VQPO'#ChO![QPO'#CjO!dQQO'#CeOOQO'#Ct'#CtOOQO'#Co'#CoQVQPOOO!iQPO'#CbO!iQPO'#CfO!qQPO'#C_O#OQPO,58xO#WQPO,58{O!iQPO,59RO#]QPO,59SOOQO'#Ck'#CkOOQO,59U,59UO#eQQO,59POOQO-E6m-E6mOOQO'#DS'#DSO#jQPO,58|OOQO,59Q,59QOOQO1G.d1G.dO#rQQO1G.dOOQO1G.g1G.gOOQO1G.m1G.mOOQO'#Ci'#CiOOQO1G.n1G.nO#wQPO1G.kOOQO1G.h1G.hO$iQQO1G.hO$nQPO7+$OOOQO'#DP'#DPOOQO'#Cp'#CpO$sQPO7+$VO$zQQO7+$SOOQO<<Gj<<GjOOQO-E6n-E6nOOQO<<Gq<<GqOOQO<<Gn<<GnO%SQQO<<GnO%XQPOAN=YOOQOG22tG22t",
  stateData: "%c~OgOS~OVVOWVO`VOaVObVOiPOlQOnYOqUOtZOuROwSOxTO~Oj_O~Oj`O~OVaOWaO~OScO~OVeOWeO~OjRXkRXmRX~PVOjiOkhO~OmjO~OVlOWlO~OrnO~OjpOpoO~OSqO~OVrOWrOiPOlQOnYOqUOtZOuROwSOxTO~OSuO~OkvO~OpxO~P#wOozOpyO~OS{O~Op|O~ObaVa~",
  goto: "#WwPPx!TPxxPPxxxx!Zx!^PPP!a!lPPP!rPPPPPPPPPP!yPP!}YVOPQX[TrntQ]PR^QRm`RbTQXOS[PQTdX[QtnRwtZWOPQX[TsntQfYQgZRk_",
  nodeNames: "⚠ Prompt WeightedExpression Content Number Permutations Lora Identifier String Choice Wildcard Embedding Artist ArtistName Tag TagName Separator Break Comment",
  maxTerm: 40,
  nodeProps: [
    ["group", -10,2,5,6,7,8,9,10,11,12,14,"ChoiceEntry Expression",-3,16,17,18,"Expression"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: ",|~RoX^#Spq#Srs#wuv$fxy$kyz$p|}$}}!O%U!O!P&[!P!Q%p!Q![&[![!]&x!]!^&}!^!_'f!`!a)X!a!b)^!c!}%p#R#S%p#T#U%p#U#V)c#V#o%p#o#p,r#q#r,w#y#z#S$f$g#S#BY#BZ#S$IS$I_#S$I|$JO#S$JT$JU#S$KV$KW#S&FU&FV#S~#XYg~X^#Spq#S#y#z#S$f$g#S#BY#BZ#S$IS$I_#S$I|$JO#S$JT$JU#S$KV$KW#S&FU&FV#S~#zTOr#wrs$Zs;'S#w;'S;=`$`<%lO#w~$`OW~~$cP;=`<%l#w~$kOx~~$pOi~R$uPkP![!]$xQ$}OrQR%UOoQ`PR%ZVVP}!O%p!O!P&[!P!Q%p!Q![&[!c!}%p#R#S%p#T#o%pP%uVVP}!O%p!O!P%p!P!Q%p!Q![%p!c!}%p#R#S%p#T#o%pR&cVSQVP}!O%p!O!P&[!P!Q%p!Q![&[!c!}%p#R#S%p#T#o%p~&}Oj~~'SSb~OY&}Z;'S&};'S;=`'`<%lO&}~'cP;=`<%l&}~'iQ#V#W'o#`#a(j~'rP#[#]'u~'xP#c#d'{~(OP#]#^(R~(UP#V#W(X~([P#X#Y(_~(bPxy(e~(jOq~~(mP#c#d(p~(sP#f#g(v~(yP#T#U(|~)PP![!])S~)XOn~~)^Op~~)cOt~~)hXVP}!O%p!O!P%p!P!Q%p!Q![%p!c!}%p#R#S%p#T#f%p#f#g*T#g#o%p~*YXVP}!O%p!O!P%p!P!Q%p!Q![%p!c!}%p#R#S%p#T#X%p#X#Y*u#Y#o%p~*zWVP}!O%p!O!P%p!P!Q%p!Q![%p!c!}%p#R#S%p#T#U+d#U#o%p~+iXVP}!O%p!O!P%p!P!Q%p!Q![%p!c!}%p#R#S%p#T#_%p#_#`,U#`#o%p~,]Va~VP}!O%p!O!P%p!P!Q%p!Q![%p!c!}%p#R#S%p#T#o%p~,wOl~~,|Om~",
  tokenizers: [0, 1],
  topRules: {"Prompt":[0,1]},
  specialized: [{term: 7, get: (value):any => spec_Identifier[value] || -1}],
  tokenPrec: 198
})
