// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Prompt: 1 = 1,
  WeightedExpression: 2 = 2,
  Content: 3 = 3,
  Number: 4 = 4,
  Permutations: 5 = 5,
  Lora: 6 = 6,
  Identifier: 7 = 7,
  String: 8 = 8,
  Wildcard: 9 = 9,
  Embedding: 10 = 10,
  Artist: 11 = 11,
  ArtistName: 12 = 12,
  Tag: 13 = 13,
  TagName: 14 = 14,
  Separator: 15 = 15,
  Break: 16 = 16,
  Comment: 17 = 17
