export type ComfyUIManagerKnownCustomNode_Title =
    | "a-person-mask-generator"
    | "A8R8 ComfyUI Nodes"
    | "abg-comfyui"
    | "Advanced CLIP Text Encode"
    | "AegisFlow Utility Nodes"
    | "AIGODLIKE-ComfyUI-Studio"
    | "AIGODLIKE-COMFYUI-TRANSLATION"
    | "AlekPet/ComfyUI_Custom_Nodes_AlekPet"
    | "alkemann nodes"
    | "Allor Plugin"
    | "AnimateDiff"
    | "AnimateDiff Evolved"
    | "Anime Character Segmentation node for comfyui"
    | "antrobots-comfyUI-nodepack"
    | "As_ComfyUI_CustomNodes"
    | "asagi4/comfyui-utility-nodes"
    | "ASTERR"
    | "asymmetric-tiling-comfyui"
    | "attention-couple-ComfyUI"
    | "auto nodes layout"
    | "Auto-MBW"
    | "avatar-graph-comfyui"
    | "BilboX's ComfyUI Custom Nodes"
    | "Bmad Nodes"
    | "braintacles-nodes"
    | "bsz-cui-extras"
    | "Canvas Tab"
    | "cd-tuner_negpip-ComfyUI"
    | "Character Face Swap"
    | "Chatbox Overlay node for ComfyUI"
    | "CLIP Directional Prompt Attention"
    | "CLIPSeg"
    | "Color Enhance"
    | "Comfy AI DoubTech.ai Image Sumission Node"
    | "Comfy UI FatLabels"
    | "Comfy UI Online Loaders"
    | "Comfy UI Prompt Agent"
    | "Comfy UI QR Codes"
    | "comfy_clip_blip_node"
    | "Comfy_KepKitchenSink"
    | "Comfy_KepListStuff"
    | "Comfy_KepMatteAnything"
    | "comfy_meh"
    | "comfy_PoP"
    | "comfy-easy-grids"
    | "Comfy-LFO"
    | "comfy-nodes"
    | "Comfy-Photoshop-SD"
    | "comfy-plasma"
    | "ComfyBreakAnim"
    | "ComfyI2I"
    | "ComfyLiterals"
    | "ComfyMath"
    | "ComfyQR"
    | "ComfyQR-scanning-nodes"
    | "ComfyS3"
    | "ComfyUI - Apply LoRA Stacker with DARE"
    | "ComfyUI - Mask Bounding Box"
    | "ComfyUI - P2LDGAN Node"
    | "ComfyUI - Text Overlay Plugin"
    | "ComfyUI 3D Pose Editor"
    | "ComfyUI A1111-like Prompt Custom Node Solution"
    | "ComfyUI aichemy nodes"
    | "ComfyUI Assistant"
    | "ComfyUI Better Strings"
    | "ComfyUI Browser"
    | "ComfyUI Clear Screen"
    | "ComfyUI Cutoff"
    | "ComfyUI Deploy"
    | "ComfyUI Diffusion Color Grading"
    | "ComfyUI Discopixel Nodes"
    | "ComfyUI Easy Padding"
    | "ComfyUI Easy Use"
    | "ComfyUI Essentials"
    | "ComfyUI Extra Samplers"
    | "ComfyUI fabric"
    | "ComfyUI Fictiverse Nodes"
    | "ComfyUI Floodgate"
    | "ComfyUI for InstructIR"
    | "ComfyUI Frame Interpolation"
    | "ComfyUI Image Saver"
    | "ComfyUI Impact Pack"
    | "ComfyUI Inpaint Nodes"
    | "ComfyUI Inspire Pack"
    | "ComfyUI InstantID Faceswapper"
    | "ComfyUI Iterative Mixing Nodes"
    | "Comfyui lama remover"
    | "ComfyUI Layer Style"
    | "ComfyUI LLaVA Captioner"
    | "ComfyUI Loopchain"
    | "ComfyUI Menu Anchor"
    | "ComfyUI MotionDiff"
    | "ComfyUI Multi-Workspace"
    | "ComfyUI Neural network latent upscale custom node"
    | "ComfyUI Nodes for External Tooling"
    | "ComfyUI Noise"
    | "ComfyUI Optical Flow"
    | "ComfyUI PhotoMaker (ZHO)"
    | "ComfyUI PhotoMaker Plus"
    | "ComfyUI PickScore Nodes"
    | "ComfyUI PixelArt Detector"
    | "ComfyUI PNG Metadata"
    | "ComfyUI Preset Merger"
    | "ComfyUI Profiler"
    | "ComfyUI prompt control"
    | "ComfyUI Prompt ExtraNetworks"
    | "ComfyUI Ricing"
    | "ComfyUI roop"
    | "ComfyUI SegMoE"
    | "ComfyUI Sequential Image Loader"
    | "ComfyUI Serving toolkit"
    | "ComfyUI SimpleTools Suit"
    | "ComfyUI Slothful Attention"
    | "ComfyUI Sokes Nodes"
    | "ComfyUI Stable Video Diffusion"
    | "ComfyUI String Tools"
    | "ComfyUI Substring"
    | "ComfyUI Tab Handler"
    | "ComfyUI WD 1.4 Tagger"
    | "ComfyUI Whisper"
    | "ComfyUI Workspace Manager - Comfyspace"
    | "ComfyUI Yolov8"
    | "comfyui_ab_sampler"
    | "ComfyUI_aspect_ratios"
    | "comfyui_auto_danbooru"
    | "ComfyUI_BadgerTools"
    | "ComfyUI_Blender_Texdiff"
    | "ComfyUI_CartoonSegmentation"
    | "ComfyUI_ColorMod"
    | "ComfyUI_Comfyroll_CustomNodes"
    | "ComfyUI_DiT [WIP]"
    | "ComfyUI_Dragos_Nodes"
    | "comfyui_DSP_imagehelpers"
    | "ComfyUI_experiments"
    | "comfyui_face_parsing"
    | "ComfyUI_FastVAEDecorder_SDXL"
    | "ComfyUI_Fill-Nodes"
    | "ComfyUI_Fooocus_KSampler"
    | "ComfyUI_GLM4Node"
    | "ComfyUI_GMIC"
    | "ComfyUI_GradientDeepShrink"
    | "ComfyUI_Ib_CustomNodes"
    | "comfyui_image_io_helpers"
    | "Comfyui_image2prompt"
    | "ComfyUI_IPAdapter_plus"
    | "ComfyUI_Jags_Audiotools"
    | "ComfyUI_Jags_VectorMagic"
    | "ComfyUI_Mexx_Poster"
    | "ComfyUI_Mexx_Styler"
    | "ComfyUI_MileHighStyler"
    | "ComfyUI_mozman_nodes"
    | "ComfyUI_MSSpeech_TTS"
    | "ComfyUI_NAIDGenerator"
    | "ComfyUI_NetDist"
    | "ComfyUI_Nimbus-Pack"
    | "comfyUI_Nodes_nicolai256"
    | "ComfyUI_NoxinNodes"
    | "ComfyUI_PerpWeight"
    | "ComfyUI_Pilgram"
    | "ComfyUI_RErouter_CustomNodes"
    | "ComfyUI_rotate_image"
    | "ComfyUI_SDXL_DreamBooth_LoRA_CustomNodes"
    | "ComfyUI_Seg_VITON"
    | "ComfyUI_Segment_Mask"
    | "ComfyUI_StreamDiffusion"
    | "ComfyUI_Strimmlarns_aesthetic_score"
    | "ComfyUi_String_Function_Tree"
    | "ComfyUI_TextAssets"
    | "ComfyUI_toyxyz_test_nodes"
    | "ComfyUI_TravelSuite"
    | "comfyui_visual_anagram"
    | "ComfyUI_WordCloud"
    | "ComfyUI_zfkun"
    | "ComfyUI-0246"
    | "ComfyUI-3D-Pack"
    | "ComfyUI-Advanced-ControlNet"
    | "ComfyUI-AIT"
    | "ComfyUI-Anchors"
    | "ComfyUI-AnimateAnyone-Evolved"
    | "comfyui-art-venture"
    | "ComfyUI-ArtGallery"
    | "ComfyUI-AudioReactive"
    | "ComfyUI-AudioReactor"
    | "ComfyUI-AudioScheduler"
    | "ComfyUI-Background-Replacement"
    | "ComfyUI-bleh"
    | "ComfyUI-Bmad-DirtyUndoRedo"
    | "ComfyUI-CADS"
    | "ComfyUI-Calculation"
    | "ComfyUI-CCSR"
    | "ComfyUI-Chat-GPT-Integration"
    | "ComfyUI-Chibi-Nodes"
    | "comfyui-clip-with-break"
    | "ComfyUI-ClipScore-Nodes"
    | "ComfyUI-ComfyCouple"
    | "ComfyUI-ComfyRun"
    | "ComfyUI-ComfyWorkflows"
    | "ComfyUI-Coziness"
    | "ComfyUI-Cre8it-Nodes"
    | "ComfyUI-CSV-Loader"
    | "ComfyUI-DareMerge"
    | "ComfyUI-DDColor"
    | "ComfyUI-deepcache"
    | "ComfyUI-Diffusers"
    | "ComfyUI-DragNUWA"
    | "ComfyUI-DynamiCrafter"
    | "comfyui-easyapi-nodes"
    | "comfyui-enhanced-save-node"
    | "ComfyUI-ExLlama"
    | "ComfyUI-FaceChain"
    | "ComfyUI-Fans"
    | "ComfyUI-fastblend"
    | "ComfyUI-FBCNN"
    | "comfyui-fitsize"
    | "ComfyUI-Flowty-LDSR"
    | "ComfyUI-Gemini"
    | "comfyui-geometry"
    | "ComfyUI-GlifNodes"
    | "ComfyUI-GTSuya-Nodes"
    | "ComfyUI-Hangover-Moondream"
    | "ComfyUI-Hangover-Nodes"
    | "ComfyUI-Hiero-Nodes"
    | "ComfyUI-HQ-Image-Save"
    | "ComfyUI-I2VGEN-XL"
    | "ComfyUI-Image-Browsing"
    | "ComfyUI-Image-Filters"
    | "ComfyUI-Image-Selector"
    | "ComfyUI-Image-Tools"
    | "ComfyUI-InstantID"
    | "ComfyUI-IPAnimate"
    | "ComfyUI-JaRue"
    | "ComfyUI-Jjk-Nodes"
    | "ComfyUI-JNodes"
    | "comfyui-job-iterator"
    | "ComfyUI-KepOpenAI"
    | "ComfyUI-Keyframed"
    | "Comfyui-Lama"
    | "ComfyUI-Latent-Modifiers"
    | "ComfyUI-LexTools"
    | "ComfyUI-LightGlue"
    | "ComfyUI-Llama"
    | "ComfyUI-Logic"
    | "ComfyUI-LogicUtils"
    | "ComfyUI-Lora-Auto-Trigger-Words"
    | "ComfyUI-MagicAnimate"
    | "ComfyUI-Malefish-Custom-Scripts"
    | "ComfyUI-Manager"
    | "comfyui-mask-util"
    | "comfyui-mixlab-nodes"
    | "ComfyUI-mnemic-nodes"
    | "ComfyUI-Model-Manager"
    | "ComfyUI-Moore-AnimateAnyone"
    | "ComfyUI-Motion-Vector-Extractor"
    | "ComfyUI-MotionCtrl"
    | "ComfyUI-MotionCtrl-SVD"
    | "ComfyUI-N-Nodes"
    | "comfyui-NDI"
    | "ComfyUI-NegiTools"
    | "ComfyUI-ngrok"
    | "ComfyUI-nodes-hnmr"
    | "ComfyUi-NoodleWebcam"
    | "ComfyUI-NSFW-Detection"
    | "ComfyUI-off-suite"
    | "ComfyUI-Openpose-Editor-Plus"
    | "ComfyUI-OtherVAEs"
    | "ComfyUI-ownimage"
    | "ComfyUI-Paint-by-Example"
    | "ComfyUI-Panda3d"
    | "comfyui-photoshop"
    | "comfyui-popup_preview"
    | "ComfyUI-Portrait-Maker"
    | "comfyui-portrait-master"
    | "comfyui-portrait-master-zh-cn"
    | "ComfyUI-post-processing-nodes"
    | "comfyui-previewlatent"
    | "comfyui-prompt-composer"
    | "ComfyUI-Prompt-Expansion"
    | "comfyui-prompt-format"
    | "comfyui-prompt-reader-node"
    | "ComfyUI-PromptUtilities"
    | "comfyui-psd2png"
    | "ComfyUI-Pymunk"
    | "ComfyUI-Q-Align"
    | "ComfyUI-Qais-Helper"
    | "ComfyUI-Qwen-VL-API"
    | "ComfyUI-RAFT"
    | "ComfyUI-RandomSize"
    | "ComfyUI-RAVE"
    | "ComfyUI-RawSaver"
    | "ComfyUI-Remover"
    | "ComfyUI-RenderRiftNodes"
    | "comfyui-ricklove"
    | "ComfyUI-safety-checker"
    | "ComfyUI-sampler-lcm-alternative"
    | "ComfyUI-Saveaswebp"
    | "ComfyUI-SaveAVIF"
    | "ComfyUI-SDXL-EmptyLatentImage"
    | "ComfyUI-seam-carving"
    | "ComfyUI-send-Eagle(slim)"
    | "ComfyUI-Simple-Aspect-Ratio"
    | "ComfyUI-SizeFromPresets"
    | "ComfyUI-stable-wildcards"
    | "ComfyUI-Static-Primitives"
    | "ComfyUI-styles-all"
    | "ComfyUI-sudo-latent-upscale"
    | "ComfyUI-SVD"
    | "ComfyUI-SVD-ZHO (WIP)"
    | "ComfyUI-TacoNodes"
    | "ComfyUI-TeaNodes"
    | "ComfyUI-TemporaryLoader"
    | "ComfyUI-Tensor-Operations"
    | "ComfyUI-Text_Image-Composite [WIP]"
    | "ComfyUI-TextUtils"
    | "comfyUI-tool-2lab"
    | "Comfyui-Toolbox"
    | "ComfyUI-Transformers"
    | "ComfyUI-TrollSuite"
    | "ComfyUI-TTS"
    | "comfyui-ultralytics-yolo"
    | "ComfyUI-Vextra-Nodes"
    | "ComfyUI-Video-Matting"
    | "ComfyUI-VideoHelperSuite"
    | "comfyui-yanc"
    | "ComfyUI's ControlNet Auxiliary Preprocessors"
    | "ComfyUIInvisibleWatermark"
    | "ComfyUIJasonNode"
    | "ComfyWarp"
    | "ConCarneNode"
    | "Consistency Decoder"
    | "ControlNet-LLLite-ComfyUI"
    | "Core ML Suite for ComfyUI"
    | "CrasH Utils"
    | "Crystools"
    | "Crystools-save"
    | "Custom Nodes by xss"
    | "Cute Comfy"
    | "cyberdolphin"
    | "DarkPrompts"
    | "demofusion-comfyui"
    | "Derfuu_ComfyUI_ModdedNodes"
    | "diffus3/ComfyUI-extensions"
    | "Disco Diffusion"
    | "Dream Project Animation Nodes"
    | "Dream Video Batches"
    | "DynamicPrompts Custom Nodes"
    | "DZ-FaceDetailer"
    | "Eagle PNGInfo"
    | "easy-comfy-nodes"
    | "EasyCaptureNode for ComfyUI"
    | "eden_comfy_pipelines"
    | "Efficiency Nodes for ComfyUI Version 2.0+"
    | "Embedding Picker"
    | "Endless ️🌊✨ Nodes"
    | "Extended Save Image for ComfyUI"
    | "Extra Models for ComfyUI"
    | "ezXY scripts and nodes"
    | "Facerestore CF (Code Former)"
    | "FaceSwap"
    | "failfast-comfyui-extensions"
    | "fcSuite"
    | "Fearnworks Custom Nodes"
    | "feidorian-ComfyNodes"
    | "fexli-util-node-comfyui"
    | "FizzNodes"
    | "FreeU_Advanced"
    | "GPU temperature protection"
    | "graphNavigator"
    | "Hakkun-ComfyUI-nodes"
    | "Harronode"
    | "Hayo comfyui nodes"
    | "hus' utils for ComfyUI"
    | "IG Interpolation Nodes"
    | "Image chooser"
    | "Image Gallery"
    | "Image loader with subfolders"
    | "Image Resize for ComfyUI"
    | "Image to Text Node"
    | "image_control"
    | "Image-Captioning-in-ComfyUI"
    | "Image2Halftone Node for ComfyUI"
    | "ImageProcessing"
    | "ImageReward"
    | "ImagesGrid"
    | "InstaSwap Face Swap Node for ComfyUI"
    | "Integrated Nodes for ComfyUI"
    | "InterpolateEverything"
    | "Jovimetrix Composition Nodes"
    | "JPS Custom Nodes for ComfyUI"
    | "kb-comfyui-nodes"
    | "KepPromptLang"
    | "KJNodes for ComfyUI"
    | "Knodes"
    | "komojini-comfyui-nodes"
    | "KSampler GPU"
    | "LAizypainter-Exporter-ComfyUI"
    | "LaMa Preprocessor [WIP]"
    | "Latent Consistency Model for ComfyUI"
    | "Latent Mirror node for ComfyUI"
    | "Latent-Interposer"
    | "LatentToRGB"
    | "Lazy Pony Prompter"
    | "LCM_Inpaint-Outpaint_Comfy"
    | "LCMSampler-ComfyUI"
    | "LexMSDBNodes"
    | "LiamUtil"
    | "Lists Cartesian Product"
    | "Load Image From Base64 URI"
    | "LoadLoraWithTags"
    | "LoRA Tag Loader for ComfyUI"
    | "LoRA-Merger-ComfyUI"
    | "Lora-Training-in-Comfy"
    | "LoraInfo"
    | "m957ymj75urz/ComfyUI-Custom-Nodes"
    | "mape's ComfyUI Helpers"
    | "MarasIT Nodes"
    | "Marigold depth estimation in ComfyUI"
    | "Masquerade Nodes"
    | "MergeBlockWeighted_fo_ComfyUI"
    | "mihaiiancu/Inpaint"
    | "Mikey Nodes"
    | "MTB Nodes"
    | "NestedNodeBuilder"
    | "NodeGPT"
    | "noEmbryo nodes"
    | "noise latent perlinpinpin"
    | "ntdviet/comfyui-ext"
    | "nui suite"
    | "One Button Prompt"
    | "OneDiff Nodes"
    | "OpenAINode"
    | "OpenPose Editor"
    | "Ostris Nodes ComfyUI"
    | "Otonx's Custom Nodes"
    | "pants"
    | "pfaeff-comfyui"
    | "pfg-ComfyUI"
    | "Pixelization"
    | "Plush-for-ComfyUI"
    | "Pomfy - Photoshop and ComfyUI 2-way sync"
    | "Power Noise Suite for ComfyUI"
    | "PPF_Noise_ComfyUI"
    | "Preset Dimensions"
    | "Preview Subselection Node for ComfyUI"
    | "Primere nodes for ComfyUI"
    | "primitive-types"
    | "Prompt Info"
    | "prompt-generator"
    | "pythongosssss/ComfyUI-Custom-Scripts"
    | "qq-nodes-comfyui"
    | "QRNG_Node_ComfyUI"
    | "Quality of life Suit:V2"
    | "Ranbooru for ComfyUI"
    | "rcsaquino/comfyui-custom-nodes"
    | "ReActor Node for ComfyUI"
    | "Recommended Resolution Calculator"
    | "Rembg Background Removal Node for ComfyUI"
    | "ResolutionSelector for ComfyUI"
    | "Restart Sampling"
    | "RF Nodes"
    | "rgthree's ComfyUI Nodes"
    | "rk-comfy-nodes"
    | "RUI-Nodes"
    | "Save Image Extended for ComfyUI"
    | "Save Image with Generation Metadata"
    | "SaveImgPrompt"
    | "SComfyUI-Keyframe"
    | "SD-Advanced-Noise"
    | "SD-Latent-Upscaler"
    | "SDXL Auto Prompter"
    | "SDXL Prompt Styler"
    | "SDXL Prompt Styler (customized version by wolfden)"
    | "SDXL_sizing"
    | "SDXLCustomAspectRatio"
    | "SDXLResolutionPresets"
    | "Seamless tiling Node for ComfyUI"
    | "SeargeSDXL"
    | "SeeCoder [WIP]"
    | "segment anything"
    | "segment_to_mask_comfyui"
    | "select_folder_path_easy"
    | "sigmas_tools_and_the_golden_scheduler"
    | "Simple Math"
    | "Simple Wildcard"
    | "simple wildcard for ComfyUI"
    | "SimpleTiles"
    | "smZNodes"
    | "SpliceTools"
    | "SRL's nodes"
    | "stability-ComfyUI-nodes"
    | "Stable Diffusion Dynamic Thresholding (CFG Scale Fix)"
    | "StableZero123-comfyui"
    | "Steerable Motion"
    | "StyleAligned for ComfyUI"
    | "Styles CSV Loader Extension for ComfyUI"
    | "Syrian Falcon Nodes"
    | "tdxh_node_comfyui"
    | "TEMP_ComfyUI-BRIA_AI-RMBG"
    | "Text to video for Stable Video Diffusion in ComfyUI"
    | "TGu Utilities"
    | "TheAlly's Custom Nodes"
    | "Tiled Diffusion & VAE for ComfyUI"
    | "Tiled sampling for ComfyUI"
    | "tiled_ksampler"
    | "TiledIPAdapter"
    | "tinyterraNodes"
    | "Touchpad two-finger gesture support for macOS"
    | "tri3d-comfyui-nodes"
    | "trNodes"
    | "UltimateSDUpscale"
    | "Use Everywhere (UE Nodes)"
    | "Variables for Comfy UI"
    | "Variation seeds"
    | "Various ComfyUI Nodes by Type"
    | "Vid2vid"
    | "Visual Area Conditioning / Latent composition"
    | "VLM_nodes"
    | "WAS Node Suite"
    | "WAS_Extras"
    | "Waveform Extensions"
    | "WebDev9000-Nodes"
    | "WebUI Monaco Prompt"
    | "Wildcards"
    | "wlsh_nodes"
    | "y.k.'s ComfyUI node suite"
    | "YARS: Yet Another Resolution Selector"
    | "ymc-node-suite-comfyui"
    | "zhihuige-nodes-comfyui"
    | "ZSuite"
    | "Zuellni/ComfyUI-Custom-Nodes"

export type ComfyUIManagerKnownCustomNode_Files =
    | ""
    | "https://civitai.com/api/download/models/158997"
    | "https://civitai.com/api/download/models/23296"
    | "https://civitai.com/api/download/models/23467"
    | "https://civitai.com/api/download/models/23649"
    | "https://civitai.com/api/download/models/23884"
    | "https://civitai.com/api/download/models/24154"
    | "https://civitai.com/api/download/models/24679"
    | "https://civitai.com/api/download/models/25114"
    | "https://civitai.com/api/download/models/29750"
    | "https://civitai.com/api/download/models/29755"
    | "https://civitai.com/api/download/models/29772"
    | "https://civitai.com/api/download/models/29773"
    | "https://civitai.com/api/download/models/29774"
    | "https://civitai.com/api/download/models/31591"
    | "https://civitai.com/api/download/models/31618"
    | "https://civitai.com/api/download/models/32717"
    | "https://civitai.com/api/download/models/47776"
    | "https://gist.github.com/alkemann/7361b8eb966f29c8238fd323409efb68/raw/f9605be0b38d38d3e3a2988f89248ff557010076/alkemann.py"
    | "https://git.mmaker.moe/mmaker/sd-webui-color-enhance"
    | "https://github.com/0xbitches/ComfyUI-LCM"
    | "https://github.com/11cafe/comfyui-workspace-manager"
    | "https://github.com/1shadow1/hayo_comfyui_nodes/raw/main/LZCNodes.py"
    | "https://github.com/42lux/ComfyUI-safety-checker"
    | "https://github.com/54rt1n/ComfyUI-DareMerge"
    | "https://github.com/80sVectorz/ComfyUI-Static-Primitives"
    | "https://github.com/a1lazydog/ComfyUI-AudioScheduler"
    | "https://github.com/abdozmantar/ComfyUI-InstaSwap"
    | "https://github.com/AbdullahAlfaraj/Comfy-Photoshop-SD"
    | "https://github.com/AbyssYuan0/ComfyUI_BadgerTools"
    | "https://github.com/abyz22/image_control"
    | "https://github.com/Acly/comfyui-inpaint-nodes"
    | "https://github.com/Acly/comfyui-tooling-nodes"
    | "https://github.com/adieyal/comfyui-dynamicprompts"
    | "https://github.com/adriflex/ComfyUI_Blender_Texdiff"
    | "https://github.com/aegis72/aegisflow_utility_nodes"
    | "https://github.com/aegis72/comfyui-styles-all"
    | "https://github.com/ai-liam/comfyui_liam_util"
    | "https://github.com/AI2lab/comfyUI-tool-2lab"
    | "https://github.com/aianimation55/ComfyUI-FatLabels"
    | "https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Studio"
    | "https://github.com/AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION"
    | "https://github.com/ailex000/ComfyUI-Extensions/raw/main/image-gallery/imageGallery.js"
    | "https://github.com/AInseven/ComfyUI-fastblend"
    | "https://github.com/AIrjen/OneButtonPrompt"
    | "https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet"
    | "https://github.com/alexopus/ComfyUI-Image-Saver"
    | "https://github.com/ali1234/comfyui-job-iterator"
    | "https://github.com/alpertunga-bile/prompt-generator-comfyui"
    | "https://github.com/alsritter/asymmetric-tiling-comfyui"
    | "https://github.com/alt-key-project/comfyui-dream-project"
    | "https://github.com/alt-key-project/comfyui-dream-video-batches"
    | "https://github.com/Amorano/Jovimetrix"
    | "https://github.com/an90ray/ComfyUI_RErouter_CustomNodes"
    | "https://github.com/andersxa/comfyui-PromptAttention"
    | "https://github.com/ansonkao/comfyui-geometry"
    | "https://github.com/antrobot1234/antrobots-comfyUI-nodepack"
    | "https://github.com/aria1th/ComfyUI-LogicUtils"
    | "https://github.com/ArtBot2023/CharacterFaceSwap"
    | "https://github.com/ArtVentureX/comfyui-animatediff"
    | "https://github.com/asagi4/ComfyUI-CADS"
    | "https://github.com/asagi4/comfyui-prompt-control"
    | "https://github.com/asagi4/comfyui-utility-nodes"
    | "https://github.com/aszc-dev/ComfyUI-CoreMLSuite"
    | "https://github.com/AustinMroz/ComfyUI-SpliceTools"
    | "https://github.com/avatechai/avatar-graph-comfyui"
    | "https://github.com/azure-dragon-ai/ComfyUI-ClipScore-Nodes"
    | "https://github.com/BadCafeCode/masquerade-nodes-comfyui"
    | "https://github.com/badjeff/comfyui_lora_tag_loader"
    | "https://github.com/banodoco/steerable-motion"
    | "https://github.com/bash-j/mikey_nodes"
    | "https://github.com/bedovyy/ComfyUI_NAIDGenerator"
    | "https://github.com/Beinsezii/bsz-cui-extras"
    | "https://github.com/BennyKok/comfyui-deploy"
    | "https://github.com/biegert/ComfyUI-CLIPSeg/raw/main/custom_nodes/clipseg.py"
    | "https://github.com/Bikecicle/ComfyUI-Waveform-Extensions/raw/main/EXT_AudioManipulation.py"
    | "https://github.com/Bikecicle/ComfyUI-Waveform-Extensions/raw/main/EXT_VariationUtils.py"
    | "https://github.com/bilal-arikan/ComfyUI_TextAssets"
    | "https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb"
    | "https://github.com/BlenderNeko/ComfyUI_Cutoff"
    | "https://github.com/BlenderNeko/ComfyUI_Noise"
    | "https://github.com/BlenderNeko/ComfyUI_SeeCoder"
    | "https://github.com/BlenderNeko/ComfyUI_TiledKSampler"
    | "https://github.com/blepping/ComfyUI-bleh"
    | "https://github.com/bmad4ever/comfyui_ab_samplercustom"
    | "https://github.com/bmad4ever/comfyui_bmad_nodes"
    | "https://github.com/bmad4ever/comfyui_lists_cartesian_product"
    | "https://github.com/bmad4ever/ComfyUI-Bmad-DirtyUndoRedo"
    | "https://github.com/bradsec/ComfyUI_ResolutionSelector"
    | "https://github.com/braintacles/braintacles-comfyui-nodes"
    | "https://github.com/brianfitzgerald/style_aligned_comfy"
    | "https://github.com/bronkula/comfyui-fitsize"
    | "https://github.com/bruefire/ComfyUI-SeqImageLoader"
    | "https://github.com/budihartono/comfyui_otonx_nodes"
    | "https://github.com/bvhari/ComfyUI_ImageProcessing"
    | "https://github.com/bvhari/ComfyUI_LatentToRGB"
    | "https://github.com/bvhari/ComfyUI_PerpWeight"
    | "https://github.com/CaptainGrock/ComfyUIInvisibleWatermark/raw/main/Invisible%20Watermark.py"
    | "https://github.com/catscandrive/comfyui-imagesubfolders/raw/main/loadImageWithSubfolders.py"
    | "https://github.com/celsojr2013/comfyui_simpletools/raw/main/google_translator.py"
    | "https://github.com/celsojr2013/comfyui_simpletools/raw/main/parameters.py"
    | "https://github.com/celsojr2013/comfyui_simpletools/raw/main/resolution_solver.py"
    | "https://github.com/ceruleandeep/ComfyUI-LLaVA-Captioner"
    | "https://github.com/Chan-0312/ComfyUI-IPAnimate"
    | "https://github.com/chaojie/ComfyUI-DragNUWA"
    | "https://github.com/chaojie/ComfyUI-DynamiCrafter"
    | "https://github.com/chaojie/ComfyUI-I2VGEN-XL"
    | "https://github.com/chaojie/ComfyUI-LightGlue"
    | "https://github.com/chaojie/ComfyUI-Moore-AnimateAnyone"
    | "https://github.com/chaojie/ComfyUI-Motion-Vector-Extractor"
    | "https://github.com/chaojie/ComfyUI-MotionCtrl"
    | "https://github.com/chaojie/ComfyUI-MotionCtrl-SVD"
    | "https://github.com/chaojie/ComfyUI-Panda3d"
    | "https://github.com/chaojie/ComfyUI-Pymunk"
    | "https://github.com/chaojie/ComfyUI-RAFT"
    | "https://github.com/Chaoses-Ib/ComfyUI_Ib_CustomNodes"
    | "https://github.com/chflame163/ComfyUI_LayerStyle"
    | "https://github.com/chflame163/ComfyUI_MSSpeech_TTS"
    | "https://github.com/chflame163/ComfyUI_WordCloud"
    | "https://github.com/chibiace/ComfyUI-Chibi-Nodes"
    | "https://github.com/chrisgoringe/cg-image-picker"
    | "https://github.com/chrisgoringe/cg-noise"
    | "https://github.com/chrisgoringe/cg-prompt-info"
    | "https://github.com/chrisgoringe/cg-use-everywhere"
    | "https://github.com/chrish-slingshot/CrasHUtils"
    | "https://github.com/city96/ComfyUI_ColorMod"
    | "https://github.com/city96/ComfyUI_DiT"
    | "https://github.com/city96/ComfyUI_ExtraModels"
    | "https://github.com/city96/ComfyUI_NetDist"
    | "https://github.com/city96/SD-Advanced-Noise"
    | "https://github.com/city96/SD-Latent-Interposer"
    | "https://github.com/city96/SD-Latent-Upscaler"
    | "https://github.com/civitai/comfy-nodes"
    | "https://github.com/Clybius/ComfyUI-Extra-Samplers"
    | "https://github.com/Clybius/ComfyUI-Latent-Modifiers"
    | "https://github.com/comfyanonymous/ComfyUI_experiments"
    | "https://github.com/concarne000/ConCarneNode"
    | "https://github.com/coreyryanhanson/ComfyQR"
    | "https://github.com/coreyryanhanson/ComfyQR-scanning-nodes"
    | "https://github.com/CosmicLaca/ComfyUI_Primere_Nodes"
    | "https://github.com/crystian/ComfyUI-Crystools"
    | "https://github.com/crystian/ComfyUI-Crystools-save"
    | "https://github.com/cubiq/ComfyUI_essentials"
    | "https://github.com/cubiq/ComfyUI_IPAdapter_plus"
    | "https://github.com/cubiq/ComfyUI_SimpleMath"
    | "https://github.com/CYBERLOOM-INC/ComfyUI-nodes-hnmr"
    | "https://github.com/dagthomas/comfyui_dagthomas"
    | "https://github.com/Danand/ComfyUI-ComfyCouple"
    | "https://github.com/daniel-lewis-ab/ComfyUI-Llama"
    | "https://github.com/daniel-lewis-ab/ComfyUI-TTS"
    | "https://github.com/darkpixel/darkprompts"
    | "https://github.com/davask/ComfyUI-MarasIT-Nodes"
    | "https://github.com/dave-palt/comfyui_DSP_imagehelpers"
    | "https://github.com/Davemane42/ComfyUI_Dave_CustomNode"
    | "https://github.com/dawangraoming/ComfyUI_ksampler_gpu/raw/main/ksampler_gpu.py"
    | "https://github.com/daxthin/DZ-FaceDetailer"
    | "https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes"
    | "https://github.com/deroberon/demofusion-comfyui"
    | "https://github.com/deroberon/StableZero123-comfyui"
    | "https://github.com/dfl/comfyui-clip-with-break"
    | "https://github.com/diffus3/ComfyUI-extensions/raw/main/multiReroute/multireroute.js"
    | "https://github.com/diffus3/ComfyUI-extensions/raw/main/setget/setget.js"
    | "https://github.com/DigitalIO/ComfyUI-stable-wildcards"
    | "https://github.com/DimaChaichan/LAizypainter-Exporter-ComfyUI"
    | "https://github.com/dimtoneff/ComfyUI-PixelArt-Detector"
    | "https://github.com/diontimmer/ComfyUI-Vextra-Nodes"
    | "https://github.com/discopixel-studio/comfyui-discopixel"
    | "https://github.com/djbielejeski/a-person-mask-generator"
    | "https://github.com/dmarx/ComfyUI-AudioReactive"
    | "https://github.com/dmarx/ComfyUI-Keyframed"
    | "https://github.com/DonBaronFactory/ComfyUI-Cre8it-Nodes"
    | "https://github.com/drago87/ComfyUI_Dragos_Nodes"
    | "https://github.com/DrJKL/ComfyUI-Anchors"
    | "https://github.com/drustan-hawk/primitive-types"
    | "https://github.com/ealkanat/comfyui_easy_padding"
    | "https://github.com/edenartlab/eden_comfy_pipelines"
    | "https://github.com/Electrofried/ComfyUI-OpenAINode"
    | "https://github.com/EllangoK/ComfyUI-post-processing-nodes"
    | "https://github.com/evanspearman/ComfyMath"
    | "https://github.com/Extraltodeus/LoadLoraWithTags"
    | "https://github.com/Extraltodeus/noise_latent_perlinpinpin"
    | "https://github.com/Extraltodeus/sigmas_tools_and_the_golden_scheduler"
    | "https://github.com/failfa-st/failfast-comfyui-extensions"
    | "https://github.com/Fannovel16/comfyui_controlnet_aux"
    | "https://github.com/Fannovel16/ComfyUI-Frame-Interpolation"
    | "https://github.com/Fannovel16/ComfyUI-Loopchain"
    | "https://github.com/Fannovel16/ComfyUI-MotionDiff"
    | "https://github.com/Fannovel16/ComfyUI-Video-Matting"
    | "https://github.com/fearnworks/ComfyUI_FearnworksNodes/raw/main/fw_nodes.py"
    | "https://github.com/Feidorian/feidorian-ComfyNodes"
    | "https://github.com/fexli/fexli-util-node-comfyui"
    | "https://github.com/Fictiverse/ComfyUI_Fictiverse"
    | "https://github.com/filipemeneses/comfy_pixelization"
    | "https://github.com/filliptm/ComfyUI_Fill-Nodes"
    | "https://github.com/fitCorder/fcSuite/raw/main/fcSuite.py"
    | "https://github.com/FizzleDorf/ComfyUI_FizzNodes"
    | "https://github.com/FizzleDorf/ComfyUI-AIT"
    | "https://github.com/florestefano1975/comfyui-portrait-master"
    | "https://github.com/florestefano1975/comfyui-prompt-composer"
    | "https://github.com/flowtyone/ComfyUI-Flowty-LDSR"
    | "https://github.com/FlyingFireCo/tiled_ksampler"
    | "https://github.com/flyingshutter/As_ComfyUI_CustomNodes"
    | "https://github.com/foxtrot-roger/comfyui-rf-nodes"
    | "https://github.com/gemell1/ComfyUI_GMIC"
    | "https://github.com/ginlov/segment_to_mask_comfyui"
    | "https://github.com/giriss/comfy-image-saver"
    | "https://github.com/glibsonoran/Plush-for-ComfyUI"
    | "https://github.com/glifxyz/ComfyUI-GlifNodes"
    | "https://github.com/glowcone/comfyui-base64-to-image"
    | "https://github.com/GMapeSplat/ComfyUI_ezXY"
    | "https://github.com/godspede/ComfyUI_Substring"
    | "https://github.com/gokayfem/ComfyUI_VLM_nodes"
    | "https://github.com/Gourieff/comfyui-reactor-node"
    | "https://github.com/GTSuya-Studio/ComfyUI-Gtsuya-Nodes"
    | "https://github.com/guoyk93/yk-node-suite-comfyui"
    | "https://github.com/HAL41/ComfyUI-aichemy-nodes"
    | "https://github.com/Hangover3832/ComfyUI-Hangover-Moondream"
    | "https://github.com/Hangover3832/ComfyUI-Hangover-Nodes"
    | "https://github.com/Haoming02/comfyui-clear-screen"
    | "https://github.com/Haoming02/comfyui-diffusion-cg"
    | "https://github.com/Haoming02/comfyui-floodgate"
    | "https://github.com/Haoming02/comfyui-menu-anchor"
    | "https://github.com/Haoming02/comfyui-prompt-format"
    | "https://github.com/Haoming02/comfyui-tab-handler"
    | "https://github.com/hayden-fr/ComfyUI-Image-Browsing"
    | "https://github.com/hayden-fr/ComfyUI-Model-Manager"
    | "https://github.com/HaydenReeve/ComfyUI-Better-Strings"
    | "https://github.com/HebelHuber/comfyui-enhanced-save-node"
    | "https://github.com/hhhzzyang/Comfyui_Lama"
    | "https://github.com/Hiero207/ComfyUI-Hiero-Nodes"
    | "https://github.com/hinablue/ComfyUI_3dPoseEditor"
    | "https://github.com/hustille/ComfyUI_Fooocus_KSampler"
    | "https://github.com/hustille/ComfyUI_hus_utils"
    | "https://github.com/hylarucoder/ComfyUI-Eagle-PNGInfo"
    | "https://github.com/IDGallagher/ComfyUI-IG-Nodes"
    | "https://github.com/idrirap/ComfyUI-Lora-Auto-Trigger-Words"
    | "https://github.com/imb101/ComfyUI-FaceSwap"
    | "https://github.com/Inzaniak/comfyui-ranbooru"
    | "https://github.com/jags111/ComfyUI_Jags_Audiotools"
    | "https://github.com/jags111/ComfyUI_Jags_VectorMagic"
    | "https://github.com/jags111/efficiency-nodes-comfyui"
    | "https://github.com/jamal-alkharrat/ComfyUI_rotate_image"
    | "https://github.com/jamesWalker55/comfyui-p2ldgan"
    | "https://github.com/jamesWalker55/comfyui-various"
    | "https://github.com/JaredTherriault/ComfyUI-JNodes"
    | "https://github.com/JcandZero/ComfyUI_GLM4Node"
    | "https://github.com/Jcd1230/rembg-comfyui-node"
    | "https://github.com/JerryOrbachJr/ComfyUI-RandomSize"
    | "https://github.com/jesenzhang/ComfyUI_StreamDiffusion"
    | "https://github.com/jitcoder/lora-info"
    | "https://github.com/jjkramhoeft/ComfyUI-Jjk-Nodes"
    | "https://github.com/jmkl/ComfyUI-ricing"
    | "https://github.com/jojkaart/ComfyUI-sampler-lcm-alternative"
    | "https://github.com/Jordach/comfy-plasma"
    | "https://github.com/JPS-GER/ComfyUI_JPS-Nodes"
    | "https://github.com/jtrue/ComfyUI-JaRue"
    | "https://github.com/ka-puna/comfyui-yanc"
    | "https://github.com/kadirnar/ComfyUI-Transformers"
    | "https://github.com/Kaharos94/ComfyUI-Saveaswebp"
    | "https://github.com/Kangkang625/ComfyUI-paint-by-example"
    | "https://github.com/kenjiqq/qq-nodes-comfyui"
    | "https://github.com/kft334/Knodes"
    | "https://github.com/kijai/ComfyUI-CCSR"
    | "https://github.com/kijai/ComfyUI-DDColor"
    | "https://github.com/kijai/ComfyUI-KJNodes"
    | "https://github.com/kijai/ComfyUI-Marigold"
    | "https://github.com/kijai/ComfyUI-SVD"
    | "https://github.com/kinfolk0117/ComfyUI_GradientDeepShrink"
    | "https://github.com/kinfolk0117/ComfyUI_Pilgram"
    | "https://github.com/kinfolk0117/ComfyUI_SimpleTiles"
    | "https://github.com/kinfolk0117/ComfyUI_TiledIPAdapter"
    | "https://github.com/knuknX/ComfyUI-Image-Tools"
    | "https://github.com/kohya-ss/ControlNet-LLLite-ComfyUI"
    | "https://github.com/komojini/ComfyUI_SDXL_DreamBooth_LoRA_CustomNodes"
    | "https://github.com/komojini/komojini-comfyui-nodes"
    | "https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet"
    | "https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved"
    | "https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite"
    | "https://github.com/kwaroran/abg-comfyui"
    | "https://github.com/laksjdjf/attention-couple-ComfyUI"
    | "https://github.com/laksjdjf/cd-tuner_negpip-ComfyUI"
    | "https://github.com/laksjdjf/LCMSampler-ComfyUI"
    | "https://github.com/laksjdjf/LoRA-Merger-ComfyUI"
    | "https://github.com/laksjdjf/pfg-ComfyUI"
    | "https://github.com/LarryJane491/Image-Captioning-in-ComfyUI"
    | "https://github.com/LarryJane491/Lora-Training-in-Comfy"
    | "https://github.com/Layer-norm/comfyui-lama-remover"
    | "https://github.com/Lerc/canvas_tab"
    | "https://github.com/LEv145/images-grid-comfy-plugin"
    | "https://github.com/lilly1987/ComfyUI_node_Lilly"
    | "https://github.com/Limitex/ComfyUI-Calculation"
    | "https://github.com/Limitex/ComfyUI-Diffusers"
    | "https://github.com/lldacing/comfyui-easyapi-nodes"
    | "https://github.com/Loewen-Hob/rembg-comfyui-node-better"
    | "https://github.com/longgui0318/comfyui-mask-util"
    | "https://github.com/LonicaMewinsky/ComfyUI-MakeFrame"
    | "https://github.com/LonicaMewinsky/ComfyUI-RawSaver"
    | "https://github.com/lordgasmic/ComfyUI-Wildcards/raw/master/wildcards.py"
    | "https://github.com/lrzjason/ComfyUIJasonNode/raw/main/LatentByRatio.py"
    | "https://github.com/lrzjason/ComfyUIJasonNode/raw/main/SDXLMixSampler.py"
    | "https://github.com/ltdrdata/ComfyUI-Impact-Pack"
    | "https://github.com/ltdrdata/ComfyUI-Inspire-Pack"
    | "https://github.com/ltdrdata/ComfyUI-Manager"
    | "https://github.com/LyazS/comfyui-anime-seg"
    | "https://github.com/m-sokes/ComfyUI-Sokes-Nodes"
    | "https://github.com/M1kep/Comfy_KepKitchenSink"
    | "https://github.com/M1kep/Comfy_KepListStuff"
    | "https://github.com/M1kep/Comfy_KepMatteAnything"
    | "https://github.com/M1kep/ComfyLiterals"
    | "https://github.com/M1kep/ComfyUI-KepOpenAI"
    | "https://github.com/M1kep/ComfyUI-OtherVAEs"
    | "https://github.com/M1kep/KepPromptLang"
    | "https://github.com/m957ymj75urz/ComfyUI-Custom-Nodes/raw/main/clip-text-encode-split/clip_text_encode_split.py"
    | "https://github.com/m957ymj75urz/ComfyUI-Custom-Nodes/raw/main/colors/colors.js"
    | "https://github.com/ManglerFTW/ComfyI2I"
    | "https://github.com/mape/ComfyUI-mape-Helpers"
    | "https://github.com/marhensa/sdxl-recommended-res-calc"
    | "https://github.com/MarkoCa1/ComfyUI_Segment_Mask"
    | "https://github.com/martijnat/comfyui-previewlatent"
    | "https://github.com/massao000/ComfyUI_aspect_ratios"
    | "https://github.com/matan1905/ComfyUI-Serving-Toolkit"
    | "https://github.com/mav-rik/facerestore_cf"
    | "https://github.com/mcmonkeyprojects/sd-dynamic-thresholding"
    | "https://github.com/meap158/ComfyUI-Background-Replacement"
    | "https://github.com/meap158/ComfyUI-GPU-temperature-protection"
    | "https://github.com/meap158/ComfyUI-Prompt-Expansion"
    | "https://github.com/melMass/comfy_mtb"
    | "https://github.com/mihaiiancu/ComfyUI_Inpaint"
    | "https://github.com/mikkel/comfyui-mask-boundingbox"
    | "https://github.com/mikkel/ComfyUI-text-overlay"
    | "https://github.com/Millyarde/Pomfy"
    | "https://github.com/Miosp/ComfyUI-FBCNN"
    | "https://github.com/MitoshiroPJ/comfyui_slothful_attention"
    | "https://github.com/mlinmg/ComfyUI-LaMA-Preprocessor"
    | "https://github.com/MNeMoNiCuZ/ComfyUI-mnemic-nodes"
    | "https://github.com/modusCell/ComfyUI-dimension-node-modusCell"
    | "https://github.com/mozman/ComfyUI_mozman_nodes"
    | "https://github.com/mpiquero7164/ComfyUI-SaveImgPrompt"
    | "https://github.com/MrForExample/ComfyUI-3D-Pack"
    | "https://github.com/MrForExample/ComfyUI-AnimateAnyone-Evolved"
    | "https://github.com/nagolinc/ComfyUI_FastVAEDecorder_SDXL"
    | "https://github.com/natto-maki/ComfyUI-NegiTools"
    | "https://github.com/NicholasMcCarthy/ComfyUI_TravelSuite"
    | "https://github.com/nicolai256/comfyUI_Nodes_nicolai256/raw/main/yugioh-presets.py"
    | "https://github.com/NimaNzrii/comfyui-photoshop"
    | "https://github.com/NimaNzrii/comfyui-popup_preview"
    | "https://github.com/ningxiaoxiao/comfyui-NDI"
    | "https://github.com/Niutonian/ComfyUi-NoodleWebcam"
    | "https://github.com/nkchocoai/ComfyUI-PromptUtilities"
    | "https://github.com/nkchocoai/ComfyUI-SizeFromPresets"
    | "https://github.com/Nlar/ComfyUI_CartoonSegmentation"
    | "https://github.com/noembryo/ComfyUI-noEmbryo"
    | "https://github.com/nosiu/comfyui-instantId-faceswap"
    | "https://github.com/NotHarroweD/Harronode"
    | "https://github.com/Nourepide/ComfyUI-Allor"
    | "https://github.com/noxinias/ComfyUI_NoxinNodes"
    | "https://github.com/ntc-ai/ComfyUI-DARE-LoRA-Merge"
    | "https://github.com/ntdviet/comfyui-ext/raw/main/custom_nodes/gcLatentTunnel/gcLatentTunnel.py"
    | "https://github.com/Nuked88/ComfyUI-N-Nodes"
    | "https://github.com/Off-Live/ComfyUI-off-suite"
    | "https://github.com/omar92/ComfyUI-QualityOfLifeSuit_Omar92"
    | "https://github.com/Onierous/QRNG_Node_ComfyUI/raw/main/qrng_node.py"
    | "https://github.com/OpenArt-AI/ComfyUI-Assistant"
    | "https://github.com/ostris/ostris_nodes_comfyui"
    | "https://github.com/ownimage/ComfyUI-ownimage"
    | "https://github.com/oyvindg/ComfyUI-TrollSuite"
    | "https://github.com/palant/extended-saveimage-comfyui"
    | "https://github.com/palant/image-resize-comfyui"
    | "https://github.com/palant/integrated-nodes-comfyui"
    | "https://github.com/pants007/comfy-pants"
    | "https://github.com/ParmanBabra/ComfyUI-Malefish-Custom-Scripts"
    | "https://github.com/paulo-coronado/comfy_clip_blip_node"
    | "https://github.com/PCMonsterx/ComfyUI-CSV-Loader"
    | "https://github.com/Pfaeff/pfaeff-comfyui"
    | "https://github.com/phineas-pta/comfyui-auto-nodes-layout"
    | "https://github.com/picturesonpictures/comfy_PoP"
    | "https://github.com/pkpkTech/ComfyUI-ngrok"
    | "https://github.com/pkpkTech/ComfyUI-SaveAVIF"
    | "https://github.com/pkpkTech/ComfyUI-TemporaryLoader"
    | "https://github.com/prozacgod/comfyui-pzc-multiworkspace"
    | "https://github.com/pythongosssss/ComfyUI-Custom-Scripts"
    | "https://github.com/pythongosssss/ComfyUI-WD14-Tagger"
    | "https://github.com/QaisMalkawi/ComfyUI-QaisHelper"
    | "https://github.com/ramyma/A8R8_ComfyUI_nodes"
    | "https://github.com/rcfcu2000/zhihuige-nodes-comfyui"
    | "https://github.com/rcsaquino/comfyui-custom-nodes"
    | "https://github.com/receyuki/comfyui-prompt-reader-node"
    | "https://github.com/RenderRift/ComfyUI-RenderRiftNodes"
    | "https://github.com/rgthree/rgthree-comfy"
    | "https://github.com/richinsley/Comfy-LFO"
    | "https://github.com/ricklove/comfyui-ricklove"
    | "https://github.com/rklaffehn/rk-comfy-nodes"
    | "https://github.com/rock-land/graphNavigator/raw/main/graphNavigator/graphNavigator.js"
    | "https://github.com/romeobuilderotti/ComfyUI-PNG-Metadata"
    | "https://github.com/rui40000/RUI-Nodes"
    | "https://github.com/Ryuukeisyou/comfyui_face_parsing"
    | "https://github.com/Ryuukeisyou/comfyui_image_io_helpers"
    | "https://github.com/s1dlx/comfy_meh/raw/main/meh.py"
    | "https://github.com/SadaleNet/CLIPTextEncodeA1111-ComfyUI/raw/master/custom_nodes/clip_text_encoder_a1111.py"
    | "https://github.com/Scholar01/ComfyUI-Keyframe"
    | "https://github.com/seanlynch/comfyui-optical-flow"
    | "https://github.com/seanlynch/srl-nodes"
    | "https://github.com/SeargeDP/SeargeSDXL"
    | "https://github.com/Ser-Hilary/SDXL_sizing/raw/main/conditioning_sizing_for_SDXL.py"
    | "https://github.com/sergekatzmann/ComfyUI_Nimbus-Pack"
    | "https://github.com/shadowcz007/comfyui-consistency-decoder"
    | "https://github.com/shadowcz007/comfyui-mixlab-nodes"
    | "https://github.com/shadowcz007/comfyui-ultralytics-yolo"
    | "https://github.com/shiimizu/ComfyUI_smZNodes"
    | "https://github.com/shiimizu/ComfyUI-PhotoMaker-Plus"
    | "https://github.com/shiimizu/ComfyUI-TiledDiffusion"
    | "https://github.com/shingo1228/ComfyUI-SDXL-EmptyLatentImage"
    | "https://github.com/shingo1228/ComfyUI-send-eagle-slim"
    | "https://github.com/shockz0rz/comfy-easy-grids"
    | "https://github.com/shockz0rz/ComfyUI_InterpolateEverything"
    | "https://github.com/Shraknard/ComfyUI-Remover"
    | "https://github.com/Siberpone/lazy-pony-prompter"
    | "https://github.com/siliconflow/onediff_comfy_nodes"
    | "https://github.com/sipherxyz/comfyui-art-venture"
    | "https://github.com/skfoo/ComfyUI-Coziness"
    | "https://github.com/SLAPaper/ComfyUI-Image-Selector"
    | "https://github.com/smagnetize/kb-comfyui-nodes"
    | "https://github.com/Smuzzies/comfyui_chatbox_overlay/raw/main/chatbox_overlay.py"
    | "https://github.com/SOELexicon/ComfyUI-LexMSDBNodes"
    | "https://github.com/SOELexicon/ComfyUI-LexTools"
    | "https://github.com/SoftMeng/ComfyUI_Mexx_Poster"
    | "https://github.com/SoftMeng/ComfyUI_Mexx_Styler"
    | "https://github.com/space-nuko/ComfyUI-Disco-Diffusion"
    | "https://github.com/space-nuko/ComfyUI-OpenPose-Editor"
    | "https://github.com/space-nuko/nui-suite"
    | "https://github.com/SpaceKendo/ComfyUI-svd_txt2vid"
    | "https://github.com/spacepxl/ComfyUI-HQ-Image-Save"
    | "https://github.com/spacepxl/ComfyUI-Image-Filters"
    | "https://github.com/spacepxl/ComfyUI-RAVE"
    | "https://github.com/spinagon/ComfyUI-seam-carving"
    | "https://github.com/spinagon/ComfyUI-seamless-tiling"
    | "https://github.com/spro/comfyui-mirror"
    | "https://github.com/ssitu/ComfyUI_fabric"
    | "https://github.com/ssitu/ComfyUI_NestedNodeBuilder"
    | "https://github.com/ssitu/ComfyUI_restart_sampling"
    | "https://github.com/ssitu/ComfyUI_roop"
    | "https://github.com/ssitu/ComfyUI_UltimateSDUpscale"
    | "https://github.com/Stability-AI/stability-ComfyUI-nodes"
    | "https://github.com/StartHua/ComfyUI_Seg_VITON"
    | "https://github.com/storyicon/comfyui_segment_anything"
    | "https://github.com/strimmlarn/ComfyUI_Strimmlarns_aesthetic_score"
    | "https://github.com/styler00dollar/ComfyUI-deepcache"
    | "https://github.com/styler00dollar/ComfyUI-sudo-latent-upscale"
    | "https://github.com/subtleGradient/TinkerBot-tech-for-ComfyUI-Touchpad"
    | "https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes"
    | "https://github.com/Sxela/ComfyWarp"
    | "https://github.com/syllebra/bilbox-comfyui"
    | "https://github.com/sylym/comfy_vid2vid"
    | "https://github.com/szhublox/ambw_comfyui"
    | "https://github.com/taabata/Comfy_Syrian_Falcon_Nodes/raw/main/SyrianFalconNodes.py"
    | "https://github.com/taabata/LCM_Inpaint-Outpaint_Comfy"
    | "https://github.com/talesofai/comfyui-browser"
    | "https://github.com/Taremin/comfyui-prompt-extranetworks"
    | "https://github.com/Taremin/comfyui-string-tools"
    | "https://github.com/Taremin/webui-monaco-prompt"
    | "https://github.com/TeaCrab/ComfyUI-TeaNodes"
    | "https://github.com/TemryL/ComfyS3"
    | "https://github.com/TGu-97/ComfyUI-TGu-utils"
    | "https://github.com/TheBarret/ZSuite"
    | "https://github.com/thecooltechguy/ComfyUI-ComfyRun"
    | "https://github.com/thecooltechguy/ComfyUI-ComfyWorkflows"
    | "https://github.com/thecooltechguy/ComfyUI-MagicAnimate"
    | "https://github.com/thecooltechguy/ComfyUI-Stable-Video-Diffusion"
    | "https://github.com/thedyze/save-image-extended-comfyui"
    | "https://github.com/theUpsider/ComfyUI-Logic"
    | "https://github.com/theUpsider/ComfyUI-Styles_CSV_Loader"
    | "https://github.com/THtianhao/ComfyUI-FaceChain"
    | "https://github.com/THtianhao/ComfyUI-Portrait-Maker"
    | "https://github.com/TinyTerra/ComfyUI_tinyterraNodes"
    | "https://github.com/tocubed/ComfyUI-AudioReactor"
    | "https://github.com/toyxyz/ComfyUI_toyxyz_test_nodes"
    | "https://github.com/TRI3D-LC/tri3d-comfyui-nodes"
    | "https://github.com/TripleHeadedMonkey/ComfyUI_MileHighStyler"
    | "https://github.com/trojblue/trNodes"
    | "https://github.com/Tropfchen/ComfyUI-Embedding_Picker"
    | "https://github.com/Tropfchen/ComfyUI-yaResolutionSelector"
    | "https://github.com/trumanwong/ComfyUI-NSFW-Detection"
    | "https://github.com/Trung0246/ComfyUI-0246"
    | "https://github.com/Ttl/ComfyUi_NNLatentUpscale"
    | "https://github.com/ttulttul/ComfyUI-Iterative-Mixer"
    | "https://github.com/ttulttul/ComfyUI-Tensor-Operations"
    | "https://github.com/tudal/Hakkun-ComfyUI-nodes/raw/main/hakkun_nodes.py"
    | "https://github.com/tusharbhutt/Endless-Nodes"
    | "https://github.com/twri/sdxl_prompt_styler"
    | "https://github.com/tzwm/comfyui-profiler"
    | "https://github.com/uarefans/ComfyUI-Fans"
    | "https://github.com/Umikaze-job/select_folder_path_easy"
    | "https://github.com/underclockeddev/ComfyUI-PreviewSubselection-Node/raw/master/preview_subselection.py"
    | "https://github.com/vanillacode314/SimpleWildcardsComfyUI"
    | "https://github.com/vienteck/ComfyUI-Chat-GPT-Integration"
    | "https://github.com/violet-chen/comfyui-psd2png"
    | "https://github.com/wallish77/wlsh_nodes"
    | "https://github.com/WASasquatch/ASTERR"
    | "https://github.com/WASasquatch/ComfyUI_Preset_Merger"
    | "https://github.com/WASasquatch/FreeU_Advanced"
    | "https://github.com/WASasquatch/PowerNoiseSuite"
    | "https://github.com/WASasquatch/PPF_Noise_ComfyUI"
    | "https://github.com/WASasquatch/WAS_Extras"
    | "https://github.com/WASasquatch/was-node-suite-comfyui"
    | "https://github.com/WebDev9000/WebDev9000-Nodes"
    | "https://github.com/whatbirdisthat/cyberdolphin"
    | "https://github.com/whmc76/ComfyUI-Openpose-Editor-Plus"
    | "https://github.com/wmatson/easy-comfy-nodes"
    | "https://github.com/wolfden/ComfyUi_PromptStylers"
    | "https://github.com/wolfden/ComfyUi_String_Function_Tree"
    | "https://github.com/wsippel/comfyui_ws/raw/main/sdxl_utility.py"
    | "https://github.com/wutipong/ComfyUI-TextUtils"
    | "https://github.com/wwwins/ComfyUI-Simple-Aspect-Ratio"
    | "https://github.com/xXAdonesXx/NodeGPT"
    | "https://github.com/yffyhk/comfyui_auto_danbooru"
    | "https://github.com/YinBailiang/MergeBlockWeighted_fo_ComfyUI"
    | "https://github.com/YMC-GitHub/ymc-node-suite-comfyui"
    | "https://github.com/yolain/ComfyUI-Easy-Use"
    | "https://github.com/yolanother/DTAIComfyImageSubmit"
    | "https://github.com/yolanother/DTAIComfyLoaders"
    | "https://github.com/yolanother/DTAIComfyPromptAgent"
    | "https://github.com/yolanother/DTAIComfyQRCodes"
    | "https://github.com/yolanother/DTAIComfyVariables"
    | "https://github.com/yolanother/DTAIImageToTextNode"
    | "https://github.com/YOUR-WORST-TACO/ComfyUI-TacoNodes"
    | "https://github.com/youyegit/tdxh_node_comfyui"
    | "https://github.com/yuvraj108c/ComfyUI-Whisper"
    | "https://github.com/ZaneA/ComfyUI-ImageReward"
    | "https://github.com/zcfrank1st/comfyui_visual_anagrams"
    | "https://github.com/zcfrank1st/Comfyui-Toolbox"
    | "https://github.com/zcfrank1st/Comfyui-Yolov8"
    | "https://github.com/zer0TF/cute-comfy"
    | "https://github.com/zfkun/ComfyUI_zfkun"
    | "https://github.com/ZHO-ZHO-ZHO/ComfyUI-ArtGallery"
    | "https://github.com/ZHO-ZHO-ZHO/ComfyUI-BRIA_AI-RMBG"
    | "https://github.com/ZHO-ZHO-ZHO/ComfyUI-Gemini"
    | "https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID"
    | "https://github.com/ZHO-ZHO-ZHO/ComfyUI-PhotoMaker-ZHO"
    | "https://github.com/ZHO-ZHO-ZHO/comfyui-portrait-master-zh-cn"
    | "https://github.com/ZHO-ZHO-ZHO/ComfyUI-Q-Align"
    | "https://github.com/ZHO-ZHO-ZHO/ComfyUI-Qwen-VL-API"
    | "https://github.com/ZHO-ZHO-ZHO/ComfyUI-SegMoE"
    | "https://github.com/ZHO-ZHO-ZHO/ComfyUI-SVD-ZHO"
    | "https://github.com/ZHO-ZHO-ZHO/ComfyUI-Text_Image-Composite"
    | "https://github.com/zhongpei/Comfyui_image2prompt"
    | "https://github.com/zhongpei/ComfyUI-InstructIR"
    | "https://github.com/zhuanqianfish/ComfyUI-EasyNode"
    | "https://github.com/Zuellni/ComfyUI-Custom-Nodes"
    | "https://github.com/Zuellni/ComfyUI-ExLlama"
    | "https://github.com/Zuellni/ComfyUI-PickScore-Nodes"
    | "https://raw.githubusercontent.com/throttlekitty/SDXLCustomAspectRatio/main/SDXLAspectRatio.py"


