import type { BaseSelectEntry } from 'src/controls/widgets/selectOne/WidgetSelectOne'

// prettier-ignore
export const gmbCols :BaseSelectEntry[] = [
    {id:'redacted',                    label:'redacted'},
    {id:'redacted',            label:'redacted'},
    {id:'redacted',           label:'redacted'},
    {id:'redacted',           label:'redacted'},
    {id:'redacted',   label:'redacted'},
    {id:'redacted',                label:'redacted'},
    {id:'redacted',               label:'redacted'},
    {id:'redacted',            label:'redacted'},
    {id:'redacted',               label:'redacted'},
    {id:'redacted',              label:'redacted'},
    {id:'redacted',          label:'redacted'},
    {id:'redacted',        label:'redacted'},
    {id:'redacted', label:'redacted'},
    {id:'redacted',       label:'redacted'},
    {id:'redacted',      label:'redacted'},
    {id:'redacted',      label:'redacted'},
    {id:'redacted',       label:'redacted'},
    {id:'redacted',       label:'redacted'},
    {id:'redacted',            label:'redacted'},
    {id:'redacted',            label:'redacted'},
    {id:'redacted',                label:'redacted'},
    {id:'redacted',            label:'redacted'},
    {id:'redacted',                label:'redacted'},
    {id:'redacted',   label:'redacted'},
    {id:'redacted', label:'redacted'},
    {id:'redacted',            label:'redacted'},
    {id:'redacted',  label:'redacted'},
    {id:'redacted',  label:'redacted'},
]
