import type { VisEdges, VisNodes } from '../ui/VisUI'
import type { ComfyNodeUID } from './ComfyNodeUID'
import type { CSScript } from './CSScript'
import type { ComfyPromptJSON } from './ComfyPrompt'
import type { Maybe } from './ComfyUtils'
import type { CSRun } from './CSRun'
import type { ScriptStep_prompt } from './ScriptStep_prompt'

// import { BranchUserApi, GitgraphUserApi } from '@gitgraph/core'
import { computed, makeObservable } from 'mobx'
import { nanoid } from 'nanoid'
import { Workspace } from './Workspace'
import { comfyColors } from './ComfyColors'
import { ComfyNode } from './CSNode'
import { ComfyNodeSchema, ComfySchema } from './ComfySchema'
import { wildcards } from '../embeds/wildcards'
import { CSImage } from './CSImage'
import { Cyto } from '../ui/graph/cyto'

export type RunMode = 'fake' | 'real'

export class ComfyGraph {
    uid = nanoid()
    get client(): Workspace { return this.project.workspace } // prettier-ignore
    get schema() { return this.client.schema } // prettier-ignore

    cyto?: Cyto
    // onNodeAdded: Maybe<(node: ComfyNode<any>) => void>
    registerNode = (node: ComfyNode<any>) => {
        this.nodesIndex.set(node.uid, node)
        this.cyto?.addNode(node)
        // this.graph.run.cyto.addNode(this)
    }
    get nodes() { return Array.from(this.nodesIndex.values()) } // prettier-ignore
    nodesIndex = new Map<string, ComfyNode<any>>()
    isRunning = false

    randomSeed() {
        return Math.floor(Math.random() * 99999999)
    }

    wildcards = wildcards

    /** return the coresponding comfy prompt  */
    get json(): ComfyPromptJSON {
        const json: ComfyPromptJSON = {}
        for (const node of this.nodes) {
            json[node.uid] = node.json
            // if (node.$schema.name === 'VAEEncode') {
            //     console.log('🔥', node.$schema.name)
            //     console.log(node.inputs.pixels)
            //     console.log(node.inputs.pixels?.$schema?.name)
            //     console.log(JSON.stringify(node.json))
            // }
        }
        return json
    }

    /** temporary proxy */
    convertToImageInput = async (x: CSImage): Promise<string> => {
        const name = await x.makeAvailableAsInput()
        console.log('[convertToImageInput]', { name })
        // @ts-ignore
        return name
        // return this.LoadImage({ image: name })
    }

    askBoolean = (msg: string, def?: Maybe<boolean>): Promise<boolean> => this.run.askBoolean(msg, def)
    askString = (msg: string, def?: Maybe<string>): Promise<string> => this.run.askString(msg, def)
    print = (...msg: any[]) => console.log('[🔥]', ...msg)

    constructor(
        //
        public project: CSScript,
        public run: CSRun,
        json: ComfyPromptJSON = {},
    ) {
        // console.log('COMFY GRAPH')
        makeObservable(this, { allImages: computed })
        for (const [uid, node] of Object.entries(json)) {
            new ComfyNode(this, uid, node)
        }
        // inject properties:
        // TODO: rewrite with a single defineProperties call
        // with propery object being defined on the client
        // to remove all this extra work
        const schema = project.schema
        for (const node of schema.nodes) {
            // console.log(`node: ${node.name}`)
            Object.defineProperty(this, node.name, {
                value: (inputs: any) =>
                    new ComfyNode(this, this.getUID(), {
                        class_type: node.name as any,
                        inputs,
                    }),
            })
        }
    }

    private _nextUID = 1
    getUID = () => (this._nextUID++).toString()
    getNodeOrCrash = (nodeID: ComfyNodeUID): ComfyNode<any> => {
        const node = this.nodesIndex.get(nodeID)
        if (node == null) throw new Error('Node not found:' + nodeID)
        return node
    }

    /** all images generated by nodes in this graph */
    get allImages(): CSImage[] {
        return this.nodes.flatMap((a) => a.images)
    }

    /** wether it should really send the prompt to the backend */
    get runningMode(): RunMode {
        return this.run.opts?.mock ? 'fake' : 'real'
    }

    // COMMIT --------------------------------------------
    async get(): Promise<ScriptStep_prompt> {
        // console.log('A')
        const step = this.run.sendPromp()
        // this.run.cyto.animate()
        // console.log('B')
        await step.finished
        // console.log('C')
        // console.log(`🐙`, step.uid, step.images.length, { step }, step.images[0].url)
        return step
    }

    // JSON_forGitGraphVisualisation = (gitgraph: GitgraphUserApi<any>) => {
    //     // extract graph
    //     const ids: TNode[] = []
    //     const edges: TEdge[] = []
    //     for (const node of this.nodesArray) {
    //         ids.push(node.uid)
    //         for (const fromUID of node._incomingNodes()) edges.push([fromUID, node.uid])
    //     }
    //     // sort it
    //     const sortedIds = toposort(ids, edges)
    //     // renderit
    //     const invisible = { renderDot: () => null, renderMessage: () => null }
    //     const cache: { [key: string]: BranchUserApi<any> } = {}
    //     const master = gitgraph.branch('master').commit(invisible)
    //     for (const id of sortedIds) {
    //         const node = this.nodes.get(id)!
    //         const branch = master.branch(node.uid)
    //         cache[id] = branch.commit({ body: node.$schema.name, renderDot: () => null, renderMessage: () => null })
    //         for (const fromUID of node._incomingNodes())
    //             cache[id] = branch.merge({ fastForward: true, branch: fromUID, commitOptions: invisible })
    //         cache[id] = branch.commit({ body: node.$schema.name })
    //     }
    // }

    /** visjs JSON format (network visualisation) */
    get JSON_forVisDataVisualisation(): { nodes: VisNodes[]; edges: VisEdges[] } {
        const json: ComfyPromptJSON = this.json
        const schemas: ComfySchema = this.schema
        const nodes: VisNodes[] = []
        const edges: VisEdges[] = []
        if (json == null) return { nodes: [], edges: [] }
        for (const [uid, node] of Object.entries(json)) {
            const schema: ComfyNodeSchema = schemas.nodesByName[node.class_type]
            const color = comfyColors[schema.category]
            nodes.push({ id: uid, label: node.class_type, color, font: { color: 'white' }, shape: 'box' })
            for (const [name, val] of Object.entries(node.inputs)) {
                if (val instanceof Array) {
                    const [from, slotIx] = val
                    const edgeID = `${from}-${uid}-${slotIx}`
                    edges.push({ id: edgeID, from, to: uid, arrows: 'to', label: name, labelHighlightBold: false, length: 200 })
                }
            }
        }
        return { nodes, edges }
    }
}
