const _ = window.require('assert')
export default _
export const fail = _.fail
export const AssertionError = _.AssertionError
export const ok = _.ok
export const equal = _.equal
export const notEqual = _.notEqual
export const deepEqual = _.deepEqual
export const notDeepEqual = _.notDeepEqual
export const deepStrictEqual = _.deepStrictEqual
export const notDeepStrictEqual = _.notDeepStrictEqual
export const strictEqual = _.strictEqual
export const notStrictEqual = _.notStrictEqual
export const throws = _.throws
export const rejects = _.rejects
export const doesNotThrow = _.doesNotThrow
export const doesNotReject = _.doesNotReject
export const ifError = _.ifError
export const match = _.match
export const doesNotMatch = _.doesNotMatch
export const CallTracker = _.CallTracker
export const strict = _.strict
