import type { LiveInstance } from '../db/LiveInstance'

import { basename, join } from 'pathe'
import { LiveRefOpt } from 'src/db/LiveRefOpt'
import { MediaImageT } from 'src/db/TYPES.gen'
import { ComfyNodeJSON } from 'src/types/ComfyPrompt'
import { assets } from 'src/utils/assets/assets'
import { exhaust } from 'src/utils/misc/ComfyUtils'
import { ComfyImageInfo } from '../types/ComfyWsApi'
import { asAbsolutePath, asRelativePath } from '../utils/fs/pathUtils'
import { _readPngSize } from '../utils/png/_readPngSize'
import { ComfyPromptL } from './ComfyPrompt'
import { ComfyWorkflowL } from './Graph'
import { ComfyNodeMetadata } from 'src/types/ComfyNodeID'

// prettier-ignore
export type ImageInfos =
    | ImageInfos_ComfyGenerated
    | ImageInfos_Local
    | ImageInfos_Base64

type ImageInfos_ComfyGenerated = {
    type: 'image-generated-by-comfy'
    comfyHostHttpURL: string
    comfyImageInfo: ComfyImageInfo
    absPath?: string /** present if the file has been cached locally */
}
type ImageInfos_Local = {
    type: 'image-local'
    absPath: AbsolutePath
}
type ImageInfos_Base64 = {
    type: 'image-base64'
    base64Url: string
}

const getComfyURLFromImageInfos = (infos: ImageInfos_ComfyGenerated) => {
    return infos.comfyHostHttpURL + '/view?' + new URLSearchParams(infos.comfyImageInfo).toString()
}

export interface MediaImageL extends LiveInstance<MediaImageT, MediaImageL> {}
export class MediaImageL {
    /** return the image filename */
    get filename() {
        const infos = this.data.infos
        if (infos == null) return 'null'
        if (infos.type === 'image-local') return basename(infos.absPath)
        if (infos.type === 'image-base64') return infos.base64Url
        if (infos.type === 'image-generated-by-comfy') return basename(infos.comfyImageInfo.filename)
        // if (infos.type === 'image-uploaded-to-comfy') return basename(infos.comfyUploadImageResult.name)
        // if (infos.type === 'video-local-ffmpeg') return basename(infos.absPath)
        exhaust(infos)
        return 'unknown'
    }

    /**
     * live reference to the prompt this image comes from
     * null if the image is not generated by comfy
     * @since v.2384
     */
    promptRef = new LiveRefOpt<this, ComfyPromptL>(this, 'promptID', () => this.db.comfy_prompts)

    /**
     * return the Comfy prompt instance from which this image was generated
     * null if the image is not generated by comfy
     * @since v.2384
     */
    get prompt(): Maybe<ComfyPromptL> {
        return this.promptRef.item
    }

    /**
     * return the workflow from which this image was generated
     * @since v.2384
     */
    get graph(): ComfyWorkflowL | undefined {
        return this.prompt?.graph.item
    }

    /** return the json of the ComfyNode that led to this image */
    get ComfyNode(): Maybe<ComfyNodeJSON> {
        const nodeID = this.data.promptNodeID
        if (nodeID == null) return null
        return this.graph?.data.comfyPromptJSON[nodeID]
    }

    /** return the metadata of the ComfyNode that led to this image */
    get ComfyNodeMetadta(): Maybe<ComfyNodeMetadata> {
        const nodeID = this.data.promptNodeID
        if (nodeID == null) return null
        return this.graph?.data.metadata[nodeID]
    }

    /** ready to be used in image fields */
    get url() {
        const infos = this.data.infos
        if (infos == null) return `file://${assets.CushyLogo_png}`
        if (infos.type === 'image-local') return `file://${infos.absPath}`
        if (infos.type === 'image-base64') return infos.base64Url
        // if (infos.type === 'video-local-ffmpeg') return `file://${infos.absPath}`
        if (infos.type === 'image-generated-by-comfy') {
            return infos.absPath //
                ? `file://${infos.absPath}`
                : getComfyURLFromImageInfos(infos)
        }
        exhaust(infos)
        return `file://${assets.CushyLogo_png}`
    }

    /** absolute path on the machine running CushyStudio */
    get absPath(): Maybe<AbsolutePath> {
        const url = this.url
        if (url.startsWith('file://')) return asAbsolutePath(url.slice('file://'.length))
    }

    // 🟢
    onCreate = (): void => {
        this.downloadImageAndSaveToDisk()
    }

    get existsLocally(): boolean {
        return this.absPath != null
    }

    private downloadImageAndSaveToDisk = async (): Promise<true> => {
        const infos = this.data.infos
        if (infos?.type !== 'image-generated-by-comfy') return true
        if (infos.absPath != null) return true

        // error recovery => should never happend
        const response = await fetch(this.url, {
            headers: { 'Content-Type': 'image/png' },
            method: 'GET',
            // responseType: ResponseType.Binary,
        })
        const binArr = await response.arrayBuffer()

        let size: Maybe<{ width: number; height: number }>
        try {
            size = _readPngSize(binArr)
            this.update
        } catch (error) {
            console.log(error)
        }
        const outputRelPath = asRelativePath(join(infos.comfyImageInfo.subfolder, infos.comfyImageInfo.filename))
        const absPath = this.st.resolve(this.st.outputFolderPath, outputRelPath)
        this.st.writeBinaryFile(absPath, Buffer.from(binArr))
        this.update({
            infos: { ...infos, absPath: absPath },
            width: size?.width,
            height: size?.height,
        })
        console.info('🖼️ image saved')
        // this.status = ImageStatus.Saved
        this._resolve(this)
        return true
    }

    // turns this into some clean abstraction
    _resolve!: (value: this) => void
    _rejects!: (reason: any) => void
    finished: Promise<this> = new Promise((resolve, rejects) => {
        this._resolve = resolve
        this._rejects = rejects
    })
}
