export type ComfyManager_KnownModelBaseTypes =
    | 'SDXL'
    | 'SD1.x'
    | 'upscale'
    | 'deepbump'
    | 'face_restore'
    | 'SVD'
    | 'zero123'
    | 'SD1.5'
    | 'SD2'
    | 'SD2.1'
    | 'SDXL VAE'
    | 'SD1.5 VAE'
    | 'SD2.1 VAE'
    | 'SSD-1B'
    | 'segmind-vega'
    | 'vit-g'
    | 'ViT-L'
    | 'ViT-H'
    | 'ViT-G'
    | 'SAM'
    | 'SEECODER'
    | 'Ultralytics'
    | 'MotionCtrl'
    | 'GFPGAN'
    | 'CodeFormer'
    | 'facexlib'
    | 'inswapper'
