// prettier-ignore
export type KnownModel_SavePath =
    | "vae_approx"                                       // x   4
    | "default"                                          // x  71
    | "upscale_models/ldsr"                              // x   1
    | "checkpoints/upscale"                              // x   1
    | "insightface"                                      // x   2
    | "deepbump"                                         // x   1
    | "face_restore"                                     // x   3
    | "checkpoints/SVD"                                  // x   2
    | "checkpoints/zero123"                              // x   1
    | "checkpoints/Stable-Cascade"                       // x   2
    | "vae/Stable-Cascade"                               // x   2
    | "unet/Stable-Cascade"                              // x   8
    | "clip/Stable-Cascade"                              // x   1
    | "checkpoints/SDXL-TURBO"                           // x   2
    | "unet/xl-inpaint-0.1"                              // x   2
    | "loras/SDXL-Lightning"                             // x   3
    | "vae/openai_consistency_decoder"                   // x   1
    | "loras/lcm/SD1.5"                                  // x   1
    | "loras/lcm/SSD-1B"                                 // x   1
    | "loras/lcm/SDXL"                                   // x   1
    | "checkpoints/segmind-vega"                         // x   1
    | "loras/segmind-vega"                               // x   1
    | "controlnet/TemporalNet1XL"                        // x   1
    | "clip_vision"                                      // x   4
    | "custom_nodes/ControlNet-LLLite-ComfyUI/models"    // x   1
    | "sams"                                             // x   3
    | "seecoders"                                        // x   3
    | "ultralytics/bbox"                                 // x   6
    | "ultralytics/segm"                                 // x  10
    | "AnimateDiff"                                      // x   2
    | "animatediff_models"                               // x  11
    | "animatediff_motion_lora"                          // x   8
    | "controlnet/SD1.5/animatediff"                     // x   2
    | "loras/SD1.5/animatediff"                          // x   1
    | "checkpoints/motionctrl"                           // x   1
    | "ipadapter"                                        // x  16
    | "loras/ipadapter"                                  // x   5
    | "custom_nodes/pfg-ComfyUI/models"                  // x   3
    | "facerestore_models"                               // x   4
    | "facedetection"                                    // x   2
    | "photomaker"                                       // x   1
    | "insightface/models/antelopev2"                    // x   5
    | "instantid"                                        // x   1
    | "controlnet/instantid"                             // x   1
    | "custom_nodes/ComfyUI-YoloWorld-EfficientSAM"      // x   2
    | "custom_nodes/ComfyUI_FaceAnalysis/dlib"           // x   2
    | "custom_nodes/ComfyUI-BRIA_AI-RMBG/RMBG-1.4" // x   1
